src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Customer_Id__c</fullName>
        <description>Customer identifier generated by Data Access service during SignUp.

Format: UUID (GUID).
Example: eb32e69e28984400b31d5a2abd075d74</description>
        <externalId>true</externalId>
        <label>Customer Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Partner_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>self lookup to link a ThirdParty Account to the DAZNPartner Account.</description>
        <label>Partner Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Partner_Unique_Identifier__c</fullName>
        <description>Unique text to identify a Partner Account (ad example: TIM)</description>
        <externalId>true</externalId>
        <label>Partner Unique Identifier</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Partner__c</fullName>
        <description>Identifier of the partner managing the customer. Only for 3rd party customers.</description>
        <label>Partner</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/API_Log__c.object
<CustomObject>
    <description>Used to capture logs about inbound and outbound API calls</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>API Logs</relationshipLabel>
        <relationshipName>API_Logs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Process_ID__c</fullName>
        <description>Used to capture work flow ID while Zuora callout</description>
        <label>Process ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Request__c</fullName>
        <label>Request</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <label>API Log</label>
    <nameField>
        <displayFormat>API-{000000}</displayFormat>
        <label>API Log Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>API Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Event__c.object
<CustomObject>
    <fields>
        <fullName>Related_Record_Id__c</fullName>
        <description>Id of the record this Event is related with</description>
        <label>Related Record Id</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>CaseCreated</fullName>
                </value>
                <value>
                    <fullName>CustomerCreated</fullName>
                </value>
                <value>
                    <fullName>CustomerUpdated</fullName>
                </value>
                <value>
                    <fullName>DeviceRegistered</fullName>
                </value>
                <value>
                    <fullName>DeviceUnregistered</fullName>
                </value>
                <value>
                    <fullName>LeadCreated</fullName>
                </value>
                <value>
                    <fullName>OrderCreated</fullName>
                </value>
                <value>
                    <fullName>OrderUpdated</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Event</label>
    <nameField>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Event_Parser__e.object
<CustomObject>
    <fields>
        <fullName>Related_Record_ID__c</fullName>
        <label>Related Record ID</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <label>Event Parser</label>
    <pluralLabel>Event Parsers</pluralLabel>
</CustomObject>

src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Agency__c</fullName>
        <label>Agency</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>LE</fullName>
                </value>
                <value>
                    <fullName>ROAMLER</fullName>
                </value>
                <value>
                    <fullName>UGW</fullName>
                </value>
                <value>
                    <fullName>KRAUSS</fullName>
                </value>
                <value>
                    <fullName>Tel 4 (LE)</fullName>
                </value>
                <value>
                    <fullName>DAZN</fullName>
                </value>
                <value>
                    <fullName>Mixi</fullName>
                </value>
                <value>
                    <fullName>Reself(Clich)</fullName>
                </value>
                <value>
                    <fullName>UKAI</fullName>
                </value>
                <value>
                    <fullName>TCN</fullName>
                </value>
                <value>
                    <fullName>PAC</fullName>
                </value>
                <value>
                    <fullName>JCOM</fullName>
                </value>
                <value>
                    <fullName>WOWOW+</fullName>
                </value>
                <value>
                    <fullName>Starcat</fullName>
                </value>
                <value>
                    <fullName>KIRIN</fullName>
                </value>
                <value>
                    <fullName>ARUJI</fullName>
                </value>
                <value>
                    <fullName>Saga Ad agency</fullName>
                </value>
                <value>
                    <fullName>Direct</fullName>
                    <isActive>false</isActive>
                    <label>Direct</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <description>this valueset contains ISO 3166-1 alpha-2 codes and country names. An alpha-2 code is an two-letter country code defined in ISO 3166-1, part of the ISO 3166 standard</description>
        <label>Country*</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Country_Name_By_Alpha_2_Code</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Lead_Id__c</fullName>
        <externalId>true</externalId>
        <label>Lead Id</label>
        <length>32</length>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>Japan_Lead</fullName>
        <active>true</active>
        <businessProcess>Japan Lead</businessProcess>
        <label>Japan Lead</label>
    </recordTypes>
    <recordTypes>
        <fullName>Standard</fullName>
        <active>true</active>
        <businessProcess>Standard</businessProcess>
        <label>Standard</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Order__c.object
<CustomObject>
    <description>Use to capture customer&apos;s Orders</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Orders</relationshipLabel>
        <relationshipName>Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Customer_Id__c</fullName>
        <description>Customer identifier generated by Data Access service during SignUp.

Format: UUID (GUID).
Example: eb32e69e28984400b31d5a2abd075d74</description>
        <externalId>true</externalId>
        <label>Customer Id</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Order_Id__c</fullName>
        <externalId>true</externalId>
        <label>Order Id</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Order</label>
    <nameField>
        <label>Order Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <recordTypes>
        <fullName>Standard</fullName>
        <active>true</active>
        <label>Standard</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Order_Item__c.object
<CustomObject>
    <description>Used to capture the Order Items</description>
    <fields>
        <fullName>Order__c</fullName>
        <label>Order</label>
        <referenceTo>Order__c</referenceTo>
        <relationshipLabel>Order Items</relationshipLabel>
        <relationshipName>Order_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Unique_Id__c</fullName>
        <externalId>true</externalId>
        <label>Unique Id</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Order Item</label>
    <nameField>
        <label>Order Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Order Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/SubscriptionProductCharge__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Account</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>One-Time</fullName>
                </value>
                <value>
                    <fullName>Recurring</fullName>
                </value>
                <value>
                    <fullName>Usage</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>DAZN Subscription Product &amp; Charge</label>
    <nameField>
        <label>Subscription Charge Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DAZN Subscription Product &amp; Charges</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/EventDomain.cls
public inherited sharing class EventDomain extends ApplicationDomain {

    public static EventDomain newInstance(List<Event__c> events) {
        return (EventDomain) Application.Domain.newInstance(events);
    }

    public EventDomain(List<Event__c> events) {
        super(events);
    }

    public override void onAfterInsert() {
        doParseEvents();
    }

    public void doParseEvents() {
        try {
            fflib_ISObjectUnitOfWork uow = (fflib_ISObjectUnitOfWork)Application.UnitOfWork.newInstance();
            List<Event_Parser__e> eventParsers = new List<Event_Parser__e>();
            for (Event__c event : (List<Event__c>)this.records) {
                eventParsers.add(new Event_Parser__e(
                    Related_Record_ID__c = event.Id
                ));
            }
            uow.registerPublishBeforeTransaction(eventParsers);
            uow.commitWork();
        } catch(Exception e){
            doParseEventsInFuture(JSON.serialize((List<Event__c>)this.records));
        }
    }

    public void doParseEventsInFuture(String serializedRecords) {
        if (!System.Test.isRunningTest()) { parseEventsInFuture(serializedRecords); }
    }

    @Future
    public static void parseEventsInFuture(String serializedRecords) {
        List<Event__c> records = (List<Event__c>)JSON.deserialize(serializedRecords, List<Event__c>.class);
        EventDomain.newInstance(records).parseEvents();
    }

    public void parseEvents() {
        try {
            Map<Id,Event__c> eventsById = new Map<Id,Event__c>((List<Event__c>)this.Records);
            List<API_Log__c> logs = ApiLogSelector.newInstance().selectByProcessId(eventsById.keySet());
            fflib_ISObjectUnitOfWork uow = Application.UnitOfWork.newInstance(new List<SObjectType>{
                    Account.SObjectType,
                    Contact.SObjectType,
                    Lead.SObjectType,
                    Order__c.SObjectType,
                    Order_Item__c.SObjectType,
                    Event__c.SObjectType
            });

            Map<String, Contact> contactByCustomerId = new Map<String, Contact>();
            Map<Id, Contact> contactByAccountId = new Map<Id, Contact>();

            for (Api_Log__c log: logs) {
                if (log?.Request__c != null) {
                    String typeOfEvent = eventsById.get(log.Process_ID__c).Type__c;
                    if (EventType.CUSTOMERCREATED.name().equalsIgnoreCase(typeOfEvent)) {
                        CustomerPayload customerPayload = (CustomerPayload) JSON.deserializeStrict(log.Request__c, CustomerPayload.class);
                        customerPayload.customerData.account.Partner_Account__r = customerPayload.customerType == CustomerType.THIRDPARTY ? new Account(Partner_Unique_Identifier__c = customerPayload.customerData.account.Partner__c) : null;
                        uow.registerNew(customerPayload.customerData.account);
                        uow.registerRelationship(customerPayload.customerData.contact, Contact.AccountId, customerPayload.customerData.account);
                        uow.registerNew(customerPayload.customerData.contact);
                    } else if (EventType.CUSTOMERUPDATED.name().equalsIgnoreCase(typeOfEvent)) {
                        CustomerPayload customerPayload = (CustomerPayload) JSON.deserializeStrict(log.Request__c, CustomerPayload.class);
                        if (customerPayload.customerData.account != null) {
                            if(customerPayload.customerData.account.Id != null) {
                                uow.registerDirty(customerPayload.customerData.account);
                            } else {
                                UpsertUnitOfWorkHelper accountUpsertWork = new UpsertUnitOfWorkHelper(Account.Customer_Id__c);
                                uow.registerWork(accountUpsertWork);
                                accountUpsertWork.registerSObjectUpsert(customerPayload.customerData.account);
                            }
                        }
                        if (customerPayload.customerData.contact != null) {
                            if(customerPayload.customerData.account.Id != null) {
                                contactByAccountId.put(customerPayload.customerData.account.Id, customerPayload.customerData.contact);
                            } else {
                                contactByCustomerId.put(customerPayload.customerData.account.Customer_Id__c, customerPayload.customerData.contact);
                            }
                        }
                    } else if (EventType.LEADCREATED.name().equalsIgnoreCase(typeOfEvent)) {
                        LeadPayload leadPayload = (LeadPayload)JSON.deserializeStrict(log.Request__c, leadPayload.class);
                        LeadService leadService = LeadService.newInstance();
                        leadPayload.leadData.lead.RecordTypeId = leadService.getRecordTypeIdByLeadType(leadPayload.leadType);
                        leadPayload.leadData.lead.LeadSource = leadService.getLeadSourceByLeadType(leadPayload.leadType);
                        leadPayload.leadData.lead.Agency__c = leadService.getAgencyByLeadType(leadPayload.leadType);
                        Database.DMLOptions dmo = new Database.DMLOptions();
                        dmo.assignmentRuleHeader.useDefaultRule = true;
                        leadPayload.leadData.lead.setOptions(dmo);
                        uow.registerNew(leadPayload.leadData.lead);
                    } else if (EventType.ORDERCREATED.name().equalsIgnoreCase(typeOfEvent)) {
                        OrderPayload orderPayload = (OrderPayload) JSON.deserialize(log.Request__c, OrderPayload.class);
                        Account accountReference = new Account(Customer_Id__c = orderPayload.order.Customer_Id__c);
                        orderPayload.order.Account__r = accountReference;
                        uow.registerNew(orderPayload.order);
                        uow.registerDirty(eventsById.get(log.Process_ID__c), Event__c.Related_Record_Id__c, orderPayload.order);
                        for (Order_Item__c orderItem : orderPayload.orderItems) {
                            uow.registerNew(orderItem, Order_Item__c.Order__c, orderPayload.order);
                        }
                    } else if (EventType.ORDERUPDATED.name().equalsIgnoreCase(typeOfEvent)) {
                        OrderPayload orderPayload = (OrderPayload) JSON.deserialize(log.Request__c, OrderPayload.class);
                        if (orderPayload.order != null) {
                            UpsertUnitOfWorkHelper orderUpsertWork = new UpsertUnitOfWorkHelper(Order__c.Order_Id__c);
                            uow.registerWork(orderUpsertWork);
                            orderUpsertWork.registerSObjectUpsert(orderPayload.order);
                        }
                        if (orderPayload.orderItems != null && !orderPayload.orderItems.isEmpty()) {
                            UpsertUnitOfWorkHelper orderItemUpsertWork = new UpsertUnitOfWorkHelper(Order_Item__c.Unique_Id__c);
                            uow.registerWork(orderItemUpsertWork);
                            orderItemUpsertWork.registerSObjectListUpsert(orderPayload.orderItems);
                        }
                    }
                }
            }
            if(!contactByAccountId.isEmpty()) {
                for (Contact con : ContactSelector.newInstance().selectPrimaryContactByAccountIds(contactByAccountId.keySet())) {
                    contactByAccountId.get(con.Account.Id).Id = con.Id;
                    uow.registerDirty(contactByAccountId.get(con.Account.Id));
                }
            }
            if (!contactByCustomerId.isEmpty()) {
                for (Contact con : ContactSelector.newInstance().selectPrimaryContactByCustomerId(contactByCustomerId.keySet())) {
                    contactByCustomerId.get(con.Account.Customer_Id__c).Id = con.Id;
                    uow.registerDirty(contactByCustomerId.get(con.Account.Customer_Id__c));
                }
            }
            uow.commitWork();
        } catch(Exception e) {
            LoggerService.logException(e)
                .doInsertExceptionLog();
        }
    }

    public class Constructor implements fflib_SObjectDomain.IConstructable {
        public fflib_SObjectDomain construct(List<SObject> sObjectList) {
            return new EventDomain(sObjectList);
        }
    }

    public class CustomerPayload implements IPayload {
        public CustomerType customerType;
        public CustomerData customerData;
        public List<SObject> getRecords() {
            List<SObject> records = new List<SObject>();
            records.add(this.customerData.account);
            records.add(this.customerData.contact);
            return records;
        }
        public String getRecordId() {
            return this
                ?.customerData
                ?.account
                .Id;
        }
        public String getIdentifier() {
            return this
                        ?.customerData
                        ?.account
                        .Customer_ID__c;
        }
        public String getRecordType() {
            for (String recordTypeName : AccountService.ACCOUNT_RECORD_TYPE_NAMES) {
                if (recordTypeName.replaceAll('_', '').equalsIgnoreCase(customerType.name())) {
                    return recordTypeName;
                }
            }
            return null;
        }
    }

    public class CustomerData {
        public Account account {
            get {
                if (account == null) {
                    throw new DomainException(String.format(System.Label.MissingRequiredProperty, new List<String>{'Account'}));
                }
                return account;
            }
            set;
        }
        public Contact contact {
            get {
                if (contact == null) {
                    throw new DomainException(String.format(System.Label.MissingRequiredProperty, new List<String>{'Contact'}));
                }
                return contact;
            }
            set;
        }
    }
    public class LeadPayload implements IPayload {
        public LeadData leadData;
        private LeadService.LeadType leadType {
            get {
                if (leadType == null) {
                    leadType = leadData?.lead?.Country__c == 'jp' ?
                        LeadService.LeadType.Japan_Lead:
                        LeadService.LeadType.Standard;
                }
                return leadType;
            }
            set;
        }
        public List<SObject> getRecords() {
            List<SObject> records = new List<SObject>();
            records.add(this.leadData.lead);
            return records;
        }
        public String getIdentifier() {
            return this
                        ?.leadData
                        ?.lead
                        .Lead_Id__c;
        }

        public String getRecordId() {
            return '';
        }
    }

    public class LeadData {
        public Lead lead {
            get {
                if (lead == null) {
                    throw new DomainException(String.format(System.Label.MissingRequiredProperty, new List<String>{'Lead'}));
                }
                return lead;
            }
            set;
        }
    }

    public class OrderPayload implements IPayload {
        public String originalXml;
        public Order__c order;
        public List<Order_Item__c> orderItems;
        public List<SObject> getRecords() {
            List<SObject> records = new List<SObject>();
            if (order == null) {
                throw new Application.ApplicationException('Failed to parse the Order__c record.');
            }
            records.add(order);
            if (orderItems != null) {
                records.addAll(orderItems);
            }
            return records;
        }
        public String getIdentifier() {
            return this
                    ?.order
                    ?.Order_Id__c;
        }

        public String getRecordId() {
            return '';
        }
    }

    public interface IPayload {
        List<SObject> getRecords();
        String getIdentifier();
        String getRecordId();
    }

    public abstract class Validator {
        void validateRecordExists(EventService.EventServiceWrapper esw) {
            if (selectByExternalId().isEmpty()) {
                if(esw.event.Type__c.containsIgnoreCase('Customer')) {
                    throw new Application.ApplicationException(String.format(System.Label.CustomerNotFound, new List<String>{ esw.payload.getIdentifier() } ));
                } else {
                    throw new Application.ApplicationException(String.format(System.Label.OrderNotFound, new List<String>{ esw.payload.getIdentifier() } ));
                }
            }
        }
        abstract List<SObject> selectByExternalId();
    }

    public class OrderValidator extends Validator {
        public EventService.EventServiceWrapper esw;

        public OrderValidator(EventService.EventServiceWrapper esw) {
            this.esw = esw;
        }

        public override List<SObject> selectByExternalId() {
            return OrderSelector.newInstance().selectByOrderId(new Set<String>{esw.payload.getIdentifier()});
        }

        public void validateRecordExists() {
            super.validateRecordExists(esw);
        }

    }

    public class AccountValidator extends Validator {
        public EventService.EventServiceWrapper esw;

        public AccountValidator(EventService.EventServiceWrapper esw) {
            this.esw = esw;
        }

        public override List<SObject> selectByExternalId() {
            if(esw.payload.getRecordId() != null) {
                return AccountSelector.newInstance().selectById(new Set<Id>{esw.payload.getRecordId()});
            }
            return AccountSelector.newInstance().selectByCustomerId(new Set<String>{esw.payload.getIdentifier()});
        }

        public void validateRecordExists() {
            super.validateRecordExists(esw);
        }

    }

    public enum EventType {
        CUSTOMERCREATED, CUSTOMERUPDATED, LEADCREATED, ORDERCREATED, ORDERUPDATED
    }
    public enum CustomerType {
        INDEPENDENTECOMMERCE, INDEPENDENTBANKTRANSFER, THIRDPARTY
    }

}