src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Account_Status__c</fullName>
        <description>Customer status.</description>
        <label>Account Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Suspended</fullName>
                    <label>Access Suspended</label>
                </value>
                <value>
                    <fullName>ActiveGrace</fullName>
                    <label>Active Grace</label>
                </value>
                <value>
                    <fullName>ActivePaid</fullName>
                    <label>Active Paid</label>
                </value>
                <value>
                    <fullName>Blocked</fullName>
                </value>
                <value>
                    <fullName>ContractEnded</fullName>
                    <label>Contract Ended</label>
                </value>
                <value>
                    <fullName>Partial</fullName>
                </value>
                <value>
                    <fullName>SubscriptionPending</fullName>
                    <label>Subscription Pending</label>
                </value>
                <value>
                    <fullName>Prospect</fullName>
                </value>
                <value>
                    <fullName>Account Provisioning</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>All_Email_Preferences__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Opt-in flag for marketing emails. Default value depends on the country of registration.</description>
        <label>All Email Preferences</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Business_Email__c</fullName>
        <description>Email for DAZN venue finder.</description>
        <label>Business Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Business_Type__c</fullName>
        <label>Business Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Business_Type</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Customer_Id__c</fullName>
        <description>Customer identifier generated by Data Access service during SignUp.

Format: UUID (GUID).
Example: eb32e69e28984400b31d5a2abd075d74</description>
        <externalId>true</externalId>
        <label>Customer Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Notification_Country_Code__c</fullName>
        <description>this field contains an ISO 3166-1 alpha-2 code, which is a two-letter country code defined in ISO 3166-1, part of the ISO 3166 standard</description>
        <label>Notification Country Code</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Country_Codes</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Notification_Language_Code__c</fullName>
        <description>This field contains a language tag, adhering the best practices as described in rfc5646</description>
        <label>Notification Language Code</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Language_Tags</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Previous_Status__c</fullName>
        <label>Previous Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Suspended</fullName>
                    <label>Access Suspended</label>
                </value>
                <value>
                    <fullName>ActiveGrace</fullName>
                    <label>Active Grace</label>
                </value>
                <value>
                    <fullName>ActivePaid</fullName>
                    <label>Active Paid</label>
                </value>
                <value>
                    <fullName>Blocked</fullName>
                </value>
                <value>
                    <fullName>ContractEnded</fullName>
                    <label>Contract Ended</label>
                </value>
                <value>
                    <fullName>Partial</fullName>
                </value>
                <value>
                    <fullName>SubscriptionPending</fullName>
                    <label>Subscription Pending</label>
                </value>
                <value>
                    <fullName>Account Provisioning</fullName>
                </value>
                <value>
                    <fullName>Prospect</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Account_Status__c</fullName>
        <formula>TEXT(Account.Account_Status__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Account Status</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Primary_Contact__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Main contact person for DAZN Sales and Customer service.</description>
        <label>Primary Contact</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/ContactSelector.cls
public inherited sharing class ContactSelector extends fflib_SObjectSelector {
    public static ContactSelector newInstance() {
        return (ContactSelector) Application.Selector.newInstance(Contact.SObjectType);
    }

    public List<Schema.SObjectField> getSObjectFieldList() {
        return new List<Schema.SObjectField> {
            Contact.Email,
            Contact.FirstName,
            Contact.Id,
            Contact.LastName
        };
    }

    public Schema.SObjectType getSObjectType() {
        return Contact.SObjectType;
    }

    public List<Contact> selectById(Set<Id> idSet) {
        return (List<Contact>) selectSObjectsById(idSet);
    }

    public List<Contact> selectPrimaryContactByEmailAddress(Set<String> fromAddresses) {
        Set<String> contactFields = new Set<String> {
            'Account.Account_Status__c',
            'Account.Business_Email__c',
            'Account.Business_Type__c',
            'Account.Notification_Country_Code__c',
            'Account.Notification_Language_Code__c'
        };
        return Database.query(
            newQueryFactory()
                .selectFields(contactFields)
                .setCondition('Primary_Contact__c = TRUE AND Email IN :fromAddresses')
                .toSOQL()
        );
    }

    public List<Contact> selectPrimaryContactByCustomerId(Set<String> customerIds) {
        Set<String> contactFields = new Set<String> {
            'Account.Customer_Id__c',
            'Account.Id',
            'Account.RecordType',
            'Account.RecordType.DeveloperName'
        };
        return Database.query(
            newQueryFactory()
                .selectFields(contactFields)
                .setCondition('Primary_Contact__c = TRUE AND Account.Customer_Id__c IN :customerIds')
                .toSOQL()
        );
    }
  
    public List<Contact> selectPrimaryContactByAccountIds(Set<Id> idSet) {
        Set<String> contactFields = new Set<String> {
            'Account.Account_Status__c',
            'Account.All_Email_Preferences__c',
            'Account.Business_Type__c',
            'Account.Name',
            'Account.Notification_Country_Code__c',
            'Account.Notification_Language_Code__c',
            'Account.Previous_Status__c',
            'Account.RecordTypeId'
        };
        return Database.query(
            newQueryFactory()
                .selectFields(contactFields)
                .setCondition('Primary_Contact__c = TRUE AND AccountId IN :idSet')
                .toSOQL()
        );
    }

    public List<Contact> selectContactsByMobilePhoneNumbers(Set<String> mobilePhoneNumbers) {
        return Database.query(
            newQueryFactory()
                .selectFields(new Set<SObjectField>{Contact.AccountId, Contact.MobilePhone})
                .setCondition('MobilePhone IN :mobilePhoneNumbers')
                .toSOQL()
        );
    }

    public List<Contact> selectContactByIds(Set<Id> idSet) {
        Set<String> contactFields = new Set<String> {
                'Account.Name',
                'Account.Account_Status__c',
                'Account.All_Email_Preferences__c',
                'Account.Business_Type__c',
                'Account.Notification_Country_Code__c',
                'Account.Notification_Language_Code__c',
                'Account.Previous_Status__c',
                'Account.RecordTypeId'
        };
        return Database.query(
                newQueryFactory()
                        .selectFields(contactFields)
                        .setCondition('Id IN :idSet')
                        .toSOQL()
        );
    }
}