src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Account_Manager_Id__c</fullName>
        <label>Account Manager Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Account_Status__c</fullName>
        <description>Customer status.</description>
        <label>Account Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Suspended</fullName>
                    <label>Access Suspended</label>
                </value>
                <value>
                    <fullName>ActiveGrace</fullName>
                    <label>Active Grace</label>
                </value>
                <value>
                    <fullName>ActivePaid</fullName>
                    <label>Active Paid</label>
                </value>
                <value>
                    <fullName>Blocked</fullName>
                </value>
                <value>
                    <fullName>ContractEnded</fullName>
                    <label>Contract Ended</label>
                </value>
                <value>
                    <fullName>Partial</fullName>
                </value>
                <value>
                    <fullName>SubscriptionPending</fullName>
                    <label>Subscription Pending</label>
                </value>
                <value>
                    <fullName>Prospect</fullName>
                </value>
                <value>
                    <fullName>Account Provisioning</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Bill_To_Email__c</fullName>
        <label>Bill To Email</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Business_Type__c</fullName>
        <label>Business Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Business_Type</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>CAF_approved__c</fullName>
        <label>CAF approved</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Content_Digest__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Content Digest</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Contract_signed__c</fullName>
        <label>Contract signed</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Customer_Id__c</fullName>
        <description>Customer identifier generated by Data Access service during SignUp.

Format: UUID (GUID).
Example: eb32e69e28984400b31d5a2abd075d74</description>
        <externalId>true</externalId>
        <label>Customer Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Notification_Country_Code__c</fullName>
        <description>this field contains an ISO 3166-1 alpha-2 code, which is a two-letter country code defined in ISO 3166-1, part of the ISO 3166 standard</description>
        <label>Notification Country Code</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Country_Codes</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Notification_Email__c</fullName>
        <description>Email address, uniquely identifies a customer.</description>
        <label>Notification Email</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Notification_Language_Code__c</fullName>
        <description>This field contains a language tag, adhering the best practices as described in rfc5646</description>
        <label>Notification Language Code</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Language_Tags</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Previous_Status__c</fullName>
        <label>Previous Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Suspended</fullName>
                    <label>Access Suspended</label>
                </value>
                <value>
                    <fullName>ActiveGrace</fullName>
                    <label>Active Grace</label>
                </value>
                <value>
                    <fullName>ActivePaid</fullName>
                    <label>Active Paid</label>
                </value>
                <value>
                    <fullName>Blocked</fullName>
                </value>
                <value>
                    <fullName>ContractEnded</fullName>
                    <label>Contract Ended</label>
                </value>
                <value>
                    <fullName>Partial</fullName>
                </value>
                <value>
                    <fullName>SubscriptionPending</fullName>
                    <label>Subscription Pending</label>
                </value>
                <value>
                    <fullName>Account Provisioning</fullName>
                </value>
                <value>
                    <fullName>Prospect</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Venue_Address_City__c</fullName>
        <label>Venue City</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Venue_Address_Country__c</fullName>
        <description>this valueset contains ISO 3166-1 alpha-2 codes and country names. An alpha-2 code is an two-letter country code defined in ISO 3166-1, part of the ISO 3166 standard</description>
        <label>Venue Country</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Country_Name_By_Alpha_2_Code</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Venue_Address_Post_Code__c</fullName>
        <label>Venue Zip/Postal Code</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Venue_Address_State_Province__c</fullName>
        <label>Venue State/Province</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Venue_Address_Street__c</fullName>
        <label>Venue Street</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Viewer_Id__c</fullName>
        <description>Additional customer identifier for anti-piracy purposes. It should be shorter yet unique version of the customer identifier.

Format: 12 alphanumeric symbols.
Example: b75d21f0eb91</description>
        <label>Viewer Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>Independent_Ecommerce</fullName>
        <active>true</active>
        <description>Independent B2B customer paying via ecommerce. Happy Hour installed in the Venue. Access to My Account. Billing directly with DAZN.</description>
        <label>Independent (ecommerce)</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Event__c.object
<CustomObject>
    <fields>
        <fullName>Record_Type__c</fullName>
        <label>Record Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Independent_Ecommerce</fullName>
                    <label>Independent (ecommerce)</label>
                </value>
                <value>
                    <fullName>Independent_Bank_Transfer</fullName>
                    <label>Independent (bank transfer)</label>
                </value>
                <value>
                    <fullName>Enterprise_Parent</fullName>
                    <label>Enterprise Parent</label>
                </value>
                <value>
                    <fullName>Enterprise_Child</fullName>
                    <label>Enterprise Child</label>
                </value>
                <value>
                    <fullName>Third_Party</fullName>
                </value>
                <value>
                    <fullName>IndependentEcommerce</fullName>
                    <isActive>false</isActive>
                    <label>IndependentEcommerce</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Validated</fullName>
                </value>
                <value>
                    <fullName>Processed</fullName>
                </value>
                <value>
                    <fullName>Processed with Errors</fullName>
                </value>
                <value>
                    <fullName>Failed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>CaseCreated</fullName>
                </value>
                <value>
                    <fullName>CustomerCreated</fullName>
                </value>
                <value>
                    <fullName>CustomerUpdated</fullName>
                </value>
                <value>
                    <fullName>DeviceRegistered</fullName>
                </value>
                <value>
                    <fullName>DeviceUnregistered</fullName>
                </value>
                <value>
                    <fullName>LeadCreated</fullName>
                </value>
                <value>
                    <fullName>OrderCreated</fullName>
                </value>
                <value>
                    <fullName>OrderUpdated</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Event</label>
    <nameField>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/AccountDomainTest.cls
@IsTest
public with sharing class AccountDomainTest {

    @IsTest
    static void changingStatusUpdatesPreviousStatusFieldTest() {
        Account account = new Account(Name = 'some kind of test', Customer_Id__c = '3214', Business_Type__c = 'Unknown', Notification_Country_Code__c = 'DE', Notification_Language_Code__c = 'de-DE',
                Account_Status__c = 'ActivePaid', Account_Manager_Id__c = '005000000000001AAA', Bill_To_Email__c = 'your.email+fakedata77415@gmail.com', CAF_approved__c = 'Yes', Contract_signed__c = 'Yes');
        insert account;

        account.Account_Status__c = 'ActiveGrace';
        update account;

        System.assertEquals('ActivePaid', [SELECT Account_Status__c, Previous_Status__c FROM Account WHERE Id = :account.Id].Previous_Status__c);
    }

    // @isTest
    // public static void testAccountWithoutEventInsert() {
    //     TestUtils.createAndInsertAccount('test acc','test@test.com');
    //     List<Account> accountsList = [SELECT Id, RecordTypeId FROM Account];

    //     System.assertEquals(1, accountsList.size());
    //     System.assertEquals(TestUtils.getDefaultRecordType(Account.SObjectType), accountsList.get(0).RecordTypeId);
    // }

    @isTest
    public static void testAccountWithEventInsert() {
        Event__c testEvent = new Event__c (
            Name = 'eb32e69e28984400b31d5a2abd075d74',
            Status__c = 'Validated',
            Record_Type__c = 'Independent_Ecommerce',
            Type__c = 'CustomerCreated'
        );

        insert testEvent;

        TestUtils.createAndInsertAccount('test acc','test@test.com');
        List<Account> accountsList = [SELECT Id, RecordType.DeveloperName FROM Account];

        System.assertEquals(1, accountsList.size());
        System.assertEquals(AccountService.INDEPENDENT_ECOMMERCE_RECORD_TYPE_NAME, accountsList.get(0).RecordType.DeveloperName);
    }

    // TODO - Jens - 18/7/2022 - This test needs to be refactored, should use data creation method from TestUtils instead
    // @IsTest
    // private static void whenValidateRequiredSObjectFieldsForExternalIsCalledWithAllRequiredFieldsForCreated() {
    //     fflib_ApexMocks mocks = new fflib_ApexMocks();
    //     ApplicationDomain domainMock = (ApplicationDomain) mocks.mock(ApplicationDomain.class);
    //     Application.Domain.setMock((fflib_ISObjectDomain)domainMock);

    //     mocks.startStubbing();
    //     mocks.when(domainMock.sObjectType()).thenReturn(Account.SObjectType);
    //     mocks.stopStubbing();

    //     Account acc = new Account(
    //         Id = fflib_IDGenerator.generate(Account.SObjectType),
    //         Name = 'test Account',
    //         Notification_Email__c = 'tes@email.com',
    //         Account_Status__c = 'ActivePaid',
    //         Business_Type__c = 'Other',
    //         Customer_id__c = '1234',
    //         Viewer_id__c = '1234',
    //         Notification_Language_Code__c = 'en-GB',
    //         Notification_Country_Code__c = 'JP',
    //         Venue_Address_Street__c = 'Street',
    //         Venue_Address_City__c = 'City',
    //         Venue_Address_Post_Code__c = '12312',
    //         Venue_Address_Country__c = 'JP',
    //         Content_Digest__c = true,
    //         Venue_Address_State_Province__c = 'Utrecht'
    //     );
    //     List<Account> testAccountList = new List<Account> { acc };


    //     String requestBodyMock = [SELECT Id, Body FROM StaticResource WHERE Name = 'dummyIndependentEcommercePayload' LIMIT 1].Body.toString();
    //     EventService.EventServiceWrapper esw = new EventService.EventServiceWrapper();
    //     esw.payload = (EventDomain.CustomerPayload) Json.deserialize(requestBodyMock, EventDomain.CustomerPayload.class);
    //     ((EventDomain.CustomerPayload)esw.payload).customerData.account = acc;
    //     esw.event = new Event__c(
    //         Type__c = EventDomain.EventType.CUSTOMERCREATED.name()
    //     );

    //     ApplicationDomain application = (ApplicationDomain) Application.Domain.newInstance(testAccountList);
    //     Exception thrownException;
    //     try {
    //         application.validateRequiredSObjectFieldsForExternal(esw);
    //     } catch (Exception ex) {
    //         thrownException = ex;
    //     }
    //     system.assertEquals(null, thrownException);
    // }

    @IsTest
    private static void itShouldGetPicklistEntries() {
        Set<String> entries = new Set<String>();
        try {
            entries.addAll(AccountDomain.newInstance(new List<Account>())
                .getPicklistEntries(
                    Schema.Account.Account_Status__c,
                    AccountService.INDEPENDENT_ECOMMERCE_RECORD_TYPE_NAME
            ));
            System.assert(entries.contains('activepaid'),'should contain activepaid.');
        } catch (Exception ex) {
            System.assert(false, 'should not get here.');
        }
    }

}