src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Business_Type__c</fullName>
        <label>Business Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Business_Type</valueSetName>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/CustomerAccount__c.object
<CustomObject>
    <description>DAZN Billing Account object.  An account is a customer account that collects all of the critical information about the customer, such as contact information, payment terms, and payment methods. You can use a customer account to track subscriptions, amendments, and transactions, such as invoices and payments.</description>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Billing Accounts</relationshipLabel>
        <relationshipName>BillingAccount</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>PaymentTerm__c</fullName>
        <label>Payment Term</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>DAZN Billing Account</label>
    <nameField>
        <label>Billing Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DAZN Billing Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/PaymentTerm__c.object
<CustomObject>
    <fields>
        <fullName>Business_Type__c</fullName>
        <label>Business Type</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Business_Type</valueSetName>
        </valueSet>
    </fields>
    <label>DAZN Payment Term</label>
    <nameField>
        <label>ProductTerm Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DAZN Payment Term</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/DAZNBillingAccountDomainTest.cls
@IsTest(IsParallel=true)
private class DAZNBillingAccountDomainTest {
    @isTest
    public static void testUpdatePaymentTerm() {
        TestUtils.createAccount('test acc','test@test.com');

        fflib_ApexMocks mocks = new fflib_ApexMocks();
        fflib_ISObjectUnitOfWork uowMock = (fflib_ISObjectUnitOfWork) mocks.mock(fflib_ISObjectUnitOfWork.class);
        AccountSelector accSelectorMock = (AccountSelector) mocks.mock(AccountSelector.class);
        DAZNPaymentTermSelector selectorMock = (DAZNPaymentTermSelector) mocks.mock(DAZNPaymentTermSelector.class);

        // Given
        Account accountRecord = TestUtils.createAccount('TestAcc','test@mail.com');
        PaymentTerm__c paymentTermRecord = new PaymentTerm__c(Name = 'Test', Business_Type__c = 'Other');
        Test.startTest();
        insert accountRecord;

        mocks.startStubbing();
        mocks.when(selectorMock.sObjectType()).thenReturn(PaymentTerm__c.SObjectType);
        mocks.when(selectorMock.selectPaymentTermByBusinessType(new Set<String> {paymentTermRecord.Business_Type__c})).thenReturn(new List<PaymentTerm__c> {paymentTermRecord});
        mocks.when(accSelectorMock.sObjectType()).thenReturn(Account.SObjectType);
        mocks.when(accSelectorMock.selectById(new Set<Id> {accountRecord.Id})).thenReturn(new List<Account> {accountRecord});
        mocks.stopStubbing();
        Application.Selector.setMock(selectorMock);
        Application.Selector.setMock(accSelectorMock);
        Application.UnitOfWork.setMock(uowMock);

        // When

        CustomerAccount__c customerAccount = new CustomerAccount__c(Account__c = accountRecord.Id);
        insert customerAccount;
        Test.stopTest();

        // Then
        ((DAZNPaymentTermSelector) mocks.verify(selectorMock)).selectPaymentTermByBusinessType(new Set<String> {paymentTermRecord.Business_Type__c});
        ((AccountSelector) mocks.verify(accSelectorMock)).selectById(new Set<Id> {accountRecord.Id});
    }
}