src/objects/API_Log__c.object
<CustomObject>
    <description>Used to capture logs about inbound and outbound API calls</description>
    <fields>
        <fullName>Callout_type__c</fullName>
        <description>Determines whether its a inbound out bound callout</description>
        <label>Callout type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Inbound</fullName>
                </value>
                <value>
                    <fullName>Outbound</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Correlation_Id__c</fullName>
        <externalId>true</externalId>
        <label>Correlation Id</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Process_ID__c</fullName>
        <description>Used to capture work flow ID while Zuora callout</description>
        <label>Process ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Request__c</fullName>
        <label>Request</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Success</fullName>
                </value>
                <value>
                    <fullName>Failed with time out</fullName>
                </value>
                <value>
                    <fullName>Failed with errors</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>API Log</label>
    <nameField>
        <displayFormat>API-{000000}</displayFormat>
        <label>API Log Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>API Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ApiLogSelector.cls
public inherited sharing class ApiLogSelector extends fflib_SObjectSelector {
    public static ApiLogSelector newInstance() {
        return (ApiLogSelector) Application.Selector.newInstance(API_Log__c.SObjectType);
    }

    public List<Schema.SObjectField> getSObjectFieldList(){
        return new List<Schema.SObjectField> {
                API_Log__c.Correlation_Id__c,
                API_Log__c.Request__c,
                API_Log__c.Process_ID__c
        };
     }

    public Schema.SObjectType getSObjectType() {
        return API_Log__c.SObjectType;
    }

    public List<API_Log__c> selectById(Set<Id> idSet){
        return (List<API_Log__c>) selectSObjectsById(idSet);
    }

    public List<API_Log__c> selectByProcessId(Set<Id> idSet){
        return Database.query(
            newQueryFactory()
                .setCondition('Process_ID__c IN :idSet')
                .toSOQL()
        );
    }

    public List<API_Log__c> selectSuccessfulOutboundLogByProcessId(Set<String> processIds) {
        return Database.query(
                newQueryFactory()
                    .setCondition('Process_ID__c IN :processIds AND Callout_type__c = \'Outbound\' AND Status__c = \'Success\'')
                    .setOrdering('CreatedDate', fflib_QueryFactory.SortOrder.DESCENDING)
                    .toSOQL());
    }

}