src/objects/API_Log__c.object
<CustomObject>
    <description>Used to capture logs about inbound and outbound API calls</description>
    <fields>
        <fullName>Callout_type__c</fullName>
        <description>Determines whether its a inbound out bound callout</description>
        <label>Callout type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Inbound</fullName>
                </value>
                <value>
                    <fullName>Outbound</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Process_ID__c</fullName>
        <description>Used to capture work flow ID while Zuora callout</description>
        <label>Process ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Request__c</fullName>
        <label>Request</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Success</fullName>
                </value>
                <value>
                    <fullName>Failed with time out</fullName>
                </value>
                <value>
                    <fullName>Failed with errors</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>API Log</label>
    <nameField>
        <displayFormat>API-{000000}</displayFormat>
        <label>API Log Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>API Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <formula>IMAGE(CASE( Status ,&apos;New&apos;,&apos;/resource/status_icons/status-new.png&apos;,&apos;Open&apos;,&apos;/resource/status_icons/status-open.png&apos;,&apos;Pending&apos;,&apos;/resource/status_icons/status-pending.png&apos;,&apos;Escalated&apos;, &apos;/resource/status_icons/status-escalated.png&apos;,&apos;Closed&apos;,&apos;/resource/status_icons/status-closed.png&apos;,&apos;&apos;),&apos;&apos;,22,22) + &apos; &apos; + Text(Status)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Status</label>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

src/objects/Knowledge__kav.object
<CustomObject>
    <articleTypeChannelDisplay>
        <articleTypeTemplates>
            <channel>App</channel>
            <template>Tab</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Prm</channel>
            <template>Tab</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Csp</channel>
            <template>Tab</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Pkb</channel>
            <template>Toc</template>
        </articleTypeTemplates>
    </articleTypeChannelDisplay>
    <label>Knowledge</label>
    <pluralLabel>Knowledge</pluralLabel>
</CustomObject>

src/classes/ApiLogSelectorTest.cls
@IsTest
private class ApiLogSelectorTest {
    @IsTest
    static void selectByProcessIdTest() {
        List<API_Log__c> apiLogs = new List<API_Log__c>();
        API_Log__c apiLog1 = new API_Log__c(Request__c = 'request1', Process_ID__c = fflib_IDGenerator.generate(Case.SObjectType));
        apiLogs.add(apiLog1);
        API_Log__c apiLog2 = new API_Log__c(Request__c = 'request2', Process_ID__c = fflib_IDGenerator.generate(Case.SObjectType));
        apiLogs.add(apiLog2);
        insert apiLogs;

        Test.startTest();
        List<API_Log__c> selectedApiLogs = ApiLogSelector.newInstance().selectByProcessId(new Set<Id>{apiLog1.Process_ID__c});
        Test.stopTest();

        System.assertEquals(1, selectedApiLogs.size());
        API_Log__c apiLog = selectedApiLogs.get(0);
        System.assertEquals(apiLog1.Id, apiLog.Id);
        System.assertEquals(apiLog1.Request__c, apiLog.Request__c);
        System.assertEquals(apiLog1.Process_ID__c, apiLog.Process_ID__c);
    }

    @IsTest
    static void selectByIdTest() {
        List<API_Log__c> apiLogs = new List<API_Log__c>();
        API_Log__c apiLog1 = new API_Log__c(Request__c = 'request1', Process_ID__c = fflib_IDGenerator.generate(Case.SObjectType));
        apiLogs.add(apiLog1);
        API_Log__c apiLog2 = new API_Log__c(Request__c = 'request2', Process_ID__c = fflib_IDGenerator.generate(Case.SObjectType));
        apiLogs.add(apiLog2);
        insert apiLogs;

        Test.startTest();
        List<API_Log__c> selectedApiLogs = ApiLogSelector.newInstance().selectById(new Set<Id>{apiLog1.Id});
        Test.stopTest();

        System.assertEquals(1, selectedApiLogs.size());
        API_Log__c apiLog = selectedApiLogs.get(0);
        System.assertEquals(apiLog1.Id, apiLog.Id);
        System.assertEquals(apiLog1.Request__c, apiLog.Request__c);
        System.assertEquals(apiLog1.Process_ID__c, apiLog.Process_ID__c);
    }

    @IsTest
    static void selectSuccessfulOutboundLogByProcessIdTest() {
        List<API_Log__c> apiLogs = new List<API_Log__c>();
        String knowledgeId = fflib_IDGenerator.generate(Knowledge__kav.SObjectType);
        API_Log__c apiLog1 = new API_Log__c(Request__c = 'request1', Process_ID__c = knowledgeId, Callout_type__c = 'Outbound', Status__c = 'Success');
        apiLogs.add(apiLog1);
        API_Log__c apiLog2 = new API_Log__c(Request__c = 'request2', Process_ID__c = knowledgeId, Callout_type__c = 'Inbound');
        apiLogs.add(apiLog2);
        API_Log__c apiLog3 = new API_Log__c(Request__c = 'request3', Process_ID__c = fflib_IDGenerator.generate(Case.SObjectType));
        apiLogs.add(apiLog3);
        insert apiLogs;

        Test.startTest();
        List<API_Log__c> selectedApiLogs = ApiLogSelector.newInstance().selectSuccessfulOutboundLogByProcessId(new Set<String>{knowledgeId});
        Test.stopTest();

        System.assertEquals(1, selectedApiLogs.size());
        API_Log__c apiLog = selectedApiLogs.get(0);
        System.assertEquals(apiLog1.Id, apiLog.Id);
        System.assertEquals(apiLog1.Request__c, apiLog.Request__c);
        System.assertEquals(apiLog1.Process_ID__c, apiLog.Process_ID__c);
    }
}