src/objects/API_Log__c.object
<CustomObject>
    <description>Used to capture logs about inbound and outbound API calls</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>API Logs</relationshipLabel>
        <relationshipName>API_Logs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Callout_endpoint__c</fullName>
        <label>Callout endpoint</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Callout_type__c</fullName>
        <description>Determines whether its a inbound out bound callout</description>
        <label>Callout type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Inbound</fullName>
                </value>
                <value>
                    <fullName>Outbound</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Request__c</fullName>
        <label>Request</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Response_Code__c</fullName>
        <label>Response Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Response_Time__c</fullName>
        <description>Response time in ms</description>
        <label>Response Time</label>
        <precision>16</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Response__c</fullName>
        <label>Response</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Retry_Count__c</fullName>
        <description>Times the callout was retried</description>
        <label>Retry Count</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Success</fullName>
                </value>
                <value>
                    <fullName>Failed with time out</fullName>
                </value>
                <value>
                    <fullName>Failed with errors</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>API Log</label>
    <nameField>
        <displayFormat>API-{000000}</displayFormat>
        <label>API Log Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>API Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Exception_Log__c.object
<CustomObject>
    <description>Used to log all exceptions</description>
    <fields>
        <fullName>Class_Name__c</fullName>
        <description>Class name on which the exception occured</description>
        <label>Class Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Exception_Message__c</fullName>
        <label>Exception Message</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Exception_Type__c</fullName>
        <label>Exception Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Method_Name__c</fullName>
        <description>Method name on which the exception occured</description>
        <label>Method Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Running_User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>User who execute the code while the exception occurred</description>
        <label>Running User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Exception_Logs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Stack_Trace_Message__c</fullName>
        <label>Stack Trace Message</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>Exception Log</label>
    <nameField>
        <displayFormat>ELI-{0000000}</displayFormat>
        <label>Exception Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Exception Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/LoggerServiceTest.cls
@IsTest
private class LoggerServiceTest {

    @IsTest
    static void logApiOutboundSuccessTest() {
        fflib_ApexMocks mocks = new fflib_ApexMocks();
        fflib_ISObjectUnitOfWork uowMock = (fflib_ISObjectUnitOfWork) mocks.mock(fflib_ISObjectUnitOfWork.class);
        Application.UnitOfWork.setMock(uowMock);

        Id account = fflib_IDGenerator.generate(Account.SObjectType);
        String endpoint = 'testEndpoint';
        String requestBody = 'requestBody';
        String responseBody = 'responseBody';
        Integer responseCode = 200;
        Integer responseTime = 50;
        Integer retryCount = 1;

        Test.startTest();
        LoggerService.newInstance().logApiOutbound()
                .setAccountId(account)
                .setCalloutEndpoint(endpoint)
                .setRequest(requestBody)
                .setResponse(responseBody)
                .setResponseCode(responseCode)
                .setResponseTime(responseTime)
                .setRetryCount(retryCount)
                .doInsertAPILog();
        Test.stopTest();

        ((fflib_ISObjectUnitOfWork)
                mocks.verify(uowMock, 1)).registerNew(
                new API_Log__c(
                        Account__c = account,
                        Callout_type__c = String.valueOf(CalloutType.Outbound),
                        Callout_endpoint__c = endpoint,
                        Request__c = requestBody,
                        Response__c = responseBody,
                        Response_Code__c = String.valueOf(responseCode),
                        Response_Time__c = responseTime,
                        Retry_Count__c = retryCount,
                        Status__c = 'Success'
                )
        );
    }

    @IsTest
    static void logApiInboundTimeoutTest() {
        fflib_ApexMocks mocks = new fflib_ApexMocks();
        fflib_ISObjectUnitOfWork uowMock = (fflib_ISObjectUnitOfWork) mocks.mock(fflib_ISObjectUnitOfWork.class);
        Application.UnitOfWork.setMock(uowMock);

        Integer responseCode = 408;

        Test.startTest();
        LoggerService.newInstance().logApiInbound()
                .setResponseCode(responseCode)
                .doInsertFutureAPILog();
        Test.stopTest();

        ((fflib_ISObjectUnitOfWork)
                mocks.verify(uowMock, 1)).registerNew(
                new API_Log__c(
                        Callout_type__c = String.valueOf(CalloutType.Inbound),
                        Response_Code__c = String.valueOf(responseCode),
                        Status__c = 'Failed with time out'
                )
        );
    }

    @IsTest
    static void logApiInboundErrorsTest() {
        fflib_ApexMocks mocks = new fflib_ApexMocks();
        fflib_ISObjectUnitOfWork uowMock = (fflib_ISObjectUnitOfWork) mocks.mock(fflib_ISObjectUnitOfWork.class);
        Application.UnitOfWork.setMock(uowMock);

        Integer responseCode = 404;

        Test.startTest();
        LoggerService.newInstance().logApiInbound()
                .setResponseCode(responseCode)
                .doInsertFutureAPILog();
        Test.stopTest();

        ((fflib_ISObjectUnitOfWork)
                mocks.verify(uowMock, 1)).registerNew(
                new API_Log__c(
                        Callout_type__c = String.valueOf(CalloutType.Inbound),
                        Response_Code__c = String.valueOf(responseCode),
                        Status__c = 'Failed with errors'
                )
        );
    }

    @IsTest
    static void logExceptionDirectlyTest() {
        fflib_ApexMocks mocks = new fflib_ApexMocks();
        fflib_ISObjectUnitOfWork uowMock = (fflib_ISObjectUnitOfWork) mocks.mock(fflib_ISObjectUnitOfWork.class);
        Application.UnitOfWork.setMock(uowMock);

        String runningUserId = fflib_IDGenerator.generate(User.SObjectType);
        String className = 'className';
        String methodName = 'methodName';
        String exceptionMessage = 'exceptionMessage';
        String typeName = 'typeName';
        String stackTrace = 'stackTrace';

        Test.startTest();
        LoggerService.newInstance().logException()
                .setRunningUser(runningUserId)
                .setClassName(className)
                .setMethodName(methodName)
                .setExceptionMessage(exceptionMessage)
                .setTypeName(typeName)
                .setStackTrace(stackTrace)
                .doInsertExceptionLog();
        Test.stopTest();

        ((fflib_ISObjectUnitOfWork)
                mocks.verify(uowMock, 1)).registerNew(
                new Exception_Log__c(
                        Running_User__c = runningUserId,
                        Class_Name__c = className,
                        Method_Name__c = methodName,
                        Exception_Message__c = exceptionMessage,
                        Exception_Type__c = typeName,
                        Stack_Trace_Message__c = stackTrace
                )
        );
    }

    @IsTest
    static void getExceptionLogTest() {
        fflib_ApexMocks mocks = new fflib_ApexMocks();
        fflib_ISObjectUnitOfWork uowMock = (fflib_ISObjectUnitOfWork) mocks.mock(fflib_ISObjectUnitOfWork.class);
        Application.UnitOfWork.setMock(uowMock);

        Exception thrownException = null;
        Exception_Log__c exceptionLog = null;

        Test.startTest();
        try {
            throw new NullPointerException();
        }
        catch (Exception ex) {
            thrownException = ex;
            exceptionLog = LoggerService.logException(ex).getExceptionLog();
        }
        Test.stopTest();

        System.assertEquals(UserInfo.getUserId(), exceptionLog.Running_User__c);
        System.assertEquals(thrownException.getMessage(), exceptionLog.Exception_Message__c);
        System.assertEquals(thrownException.getTypeName(), exceptionLog.Exception_Type__c);
        System.assertEquals(thrownException.getStackTraceString(), exceptionLog.Stack_Trace_Message__c);
    }
}