src/objects/Available_Channel__c.object
<CustomObject>
    <fields>
        <fullName>ContactUs_SubType2__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>ContactUs SubType2</label>
        <referenceTo>Contact_Us_SubType2_Option__c</referenceTo>
        <relationshipLabel>Available Channels</relationshipLabel>
        <relationshipName>Available_Channels</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Is_Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>View__c</fullName>
        <label>View</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <label>Available Channel</label>
    <nameField>
        <label>Available Channel Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Available Channels</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Contact_Us_SubType2_Option__c.object
<CustomObject>
    <fields>
        <fullName>Is_Active__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Is Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>View__c</fullName>
        <label>View</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>ContactUs SubType2 Option</label>
    <nameField>
        <label>SubType2 Key</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ContactUs SubType2 Options</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/AvailableChannelSelector.cls
public inherited sharing class AvailableChannelSelector extends fflib_SObjectSelector {
    public static AvailableChannelSelector newInstance() {
        return (AvailableChannelSelector) Application.Selector.newInstance(Available_Channel__c.SObjectType);
    }

    public List<Schema.SObjectField> getSObjectFieldList(){
        return new List<Schema.SObjectField> {
            Available_Channel__c.Id,
            Available_Channel__c.View__c
        };
     }

    public Schema.SObjectType getSObjectType() {
        return Available_Channel__c.SObjectType;
    }

    public List<Available_Channel__c> selectById(Set<Id> idSet){
        return (List<Available_Channel__c>) selectSObjectsById(idSet);
    }

    public List<Available_Channel__c> selectActiveBySubTypeIdOrName(Set<Id> idSet, Set<String> nameSet){
        fflib_QueryFactory query = newQueryFactory();
        query.setCondition('Is_Active__c = true AND (ContactUs_SubType2__c IN :idSet OR ContactUs_SubType2__r.Name IN :nameSet)');
        return (List<Available_Channel__c>) Database.query(query.toSOQL());
    }
}