src/objects/Bot_Dialog__c.object
<CustomObject>
    <fields>
        <fullName>Bot_Name__c</fullName>
        <description>API name of the Bot that this Dialog belongs to.</description>
        <label>Bot Name</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Chat_Transcript__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Chat Transcript</label>
        <referenceTo>LiveChatTranscript</referenceTo>
        <relationshipLabel>Bot Dialogs</relationshipLabel>
        <relationshipName>Bot_Dialogs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Dialog_Name__c</fullName>
        <label>Dialog Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Goal_Name__c</fullName>
        <label>Goal Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Label__c</fullName>
        <label>Label</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Solution</fullName>
                </value>
                <value>
                    <fullName>Intermediate</fullName>
                </value>
                <value>
                    <fullName>Escalate</fullName>
                </value>
                <value>
                    <fullName>Navigation</fullName>
                </value>
                <value>
                    <fullName>Next</fullName>
                </value>
                <value>
                    <fullName>Rating</fullName>
                </value>
                <value>
                    <fullName>Back</fullName>
                </value>
                <value>
                    <fullName>Confusion</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Bot Dialog</label>
    <nameField>
        <displayFormat>BD-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bot Dialogs</pluralLabel>
    <recordTypes>
        <fullName>Dialog</fullName>
        <active>true</active>
        <description>Record Type to capture Dialogs associated to a Goal</description>
        <label>Dialog</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Bot_Dialog_Instance__c.object
<CustomObject>
    <fields>
        <fullName>Chat_Transcript__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Chat Transcript</label>
        <referenceTo>LiveChatTranscript</referenceTo>
        <relationshipLabel>Bot Dialog Instances</relationshipLabel>
        <relationshipName>Bot_Dialog_Instances</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Dialog_Name__c</fullName>
        <label>Dialog Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Goal_Name__c</fullName>
        <label>Goal Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Label__c</fullName>
        <description>Label of the Dialog or the Goal because Dialog Name is the Dialog API Name with &quot;_&quot;.</description>
        <label>Label</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Abandoned</fullName>
                </value>
                <value>
                    <fullName>Back</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Escalated</fullName>
                </value>
                <value>
                    <fullName>Redirected</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <label>Bot Dialog Instance</label>
    <nameField>
        <displayFormat>BDI-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bot Dialog Instances</pluralLabel>
    <recordTypes>
        <fullName>Dialog</fullName>
        <active>true</active>
        <label>Dialog</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Bot_Intent_Case_Mapping__mdt.object
<CustomObject>
    <fields>
        <fullName>Bot_Intent__c</fullName>
        <label>Bot Intent</label>
        <length>80</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>SubType2_Key__c</fullName>
        <label>SubType2 Key</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SubType_Key__c</fullName>
        <label>SubType Key</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type_Key__c</fullName>
        <label>Type Key</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <label>Bot Intent Case Mapping</label>
    <pluralLabel>Bot Intent Case Mappings</pluralLabel>
</CustomObject>

src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <formula>IMAGE(CASE( Status ,&apos;New&apos;,&apos;/resource/status_icons/status-new.png&apos;,&apos;Open&apos;,&apos;/resource/status_icons/status-open.png&apos;,&apos;Pending&apos;,&apos;/resource/status_icons/status-pending.png&apos;,&apos;Escalated&apos;, &apos;/resource/status_icons/status-escalated.png&apos;,&apos;Closed&apos;,&apos;/resource/status_icons/status-closed.png&apos;,&apos;&apos;),&apos;&apos;,22,22) + &apos; &apos; + Text(Status)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Status</label>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

src/objects/LiveChatTranscript.object
<CustomObject>
    <fields>
        <fullName>Bot_Name__c</fullName>
        <label>Bot Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Skills__c</fullName>
        <description>Skill names from the associated requirement</description>
        <label>Skills</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ChatBotServiceTest.cls
@IsTest(IsParallel=true)
private class ChatBotServiceTest {
/*
    @IsTest
    static void callingServiceWithValidInputShouldResultInSuccess() {
        fflib_ApexMocks mocks = new fflib_ApexMocks();

        fflib_ISObjectUnitOfWork uowMock = (fflib_ISObjectUnitOfWork) mocks.mock(fflib_ISObjectUnitOfWork.class);
        LiveChatTranscriptSelector liveChatSelectorMock = (LiveChatTranscriptSelector) mocks.mock(LiveChatTranscriptSelector.class);
        BotDialogSelector botDialogSelectorMock = (BotDialogSelector) mocks.mock(BotDialogSelector.class);
        BotDialogInstanceSelector botDialogInstanceSelectorMock = (BotDialogInstanceSelector) mocks.mock(BotDialogInstanceSelector.class);

        mocks.startStubbing();
        LiveChatTranscript testTranscript = new LiveChatTranscript(
                Id = fflib_IDGenerator.generate(LiveChatTranscript.SObjectType)
        );
        Bot_Dialog__c testDialog = new Bot_Dialog__c(
                Id = fflib_IDGenerator.generate(Bot_Dialog__c.SObjectType),
                RecordTypeId = Schema.SObjectType.Bot_Dialog_Instance__c.getRecordTypeInfosByName()
                        .get(ChatBotService.RECORD_TYPE_NAME_GOAL).getRecordTypeId(),
                Goal_Name__c = 'testGoal',
                Bot_Name__c = 'testBot',
                Label__c = 'testLabel'
        );
        Bot_Dialog__c testDialog2 = new Bot_Dialog__c(
                Id = fflib_IDGenerator.generate(Bot_Dialog__c.SObjectType),
                RecordTypeId = Schema.SObjectType.Bot_Dialog_Instance__c.getRecordTypeInfosByName()
                        .get(ChatBotService.RECORD_TYPE_NAME_DIALOG).getRecordTypeId(),
                Dialog_Name__c = 'testSolution',
                Goal_Name__c = 'testGoal',
                Bot_Name__c = 'testBot',
                Type__c = 'Solution',
                Label__c = 'testLabel'
        );
        Bot_Dialog_Instance__c botInstance = new Bot_Dialog_Instance__c(
                Id = fflib_IDGenerator.generate(Bot_Dialog_Instance__c.SObjectType),
                RecordTypeId = Schema.SObjectType.Bot_Dialog_Instance__c.getRecordTypeInfosByName()
                        .get(ChatBotService.RECORD_TYPE_NAME_DIALOG).getRecordTypeId(),
                Chat_Transcript__c = testTranscript.Id,
                Dialog_Name__c = 'testSolution',
                Goal_Name__c = 'testGoal',
                Type__c = 'Solution'
        );

        BotDialogInitializationHandler.DialogInitializationInput botInput = new BotDialogInitializationHandler.DialogInitializationInput();
        botInput.currentDialogName = 'testSolution';
        botInput.sCurrentDialog = 'testDialog';
        botInput.sCurrentGoal = 'testGoal';
        botInput.routableId = testTranscript.Id;


        mocks.when(botDialogSelectorMock.sObjectType()).thenReturn(Bot_Dialog__c.SObjectType);
        mocks.when(botDialogSelectorMock.selectByDialogName(new Set<String>{'testSolution'})).thenReturn(new List<Bot_Dialog__c>{testDialog2});
        mocks.when(botDialogInstanceSelectorMock.sObjectType()).thenReturn(Bot_Dialog_Instance__c.SObjectType);
        mocks.when(botDialogInstanceSelectorMock.selectByTranscriptId(new Set<Id>{testTranscript.Id})).thenReturn(new List<Bot_Dialog_Instance__c>{botInstance});
        mocks.stopStubbing();

        Application.Selector.setMock(botDialogSelectorMock);
        Application.Selector.setMock(botDialogInstanceSelectorMock);
        Application.UnitOfWork.setMock(uowMock);

        ChatBotService.newInstance().initializeBotDialogInstance(new List<BotDialogInitializationHandler.DialogInitializationInput>{botInput}, new Set<String>{'testSolution'}, new Set<Id>{testTranscript.Id});

        ((BotDialogSelector) mocks.verify(botDialogSelectorMock, 1)).selectByDialogName(new Set<String>{'testSolution'});
        ((BotDialogInstanceSelector) mocks.verify(botDialogInstanceSelectorMock, 1)).selectByTranscriptId(new Set<Id>{testTranscript.Id});
        ((fflib_ISObjectUnitOfWork) mocks.verify(uowMock, 1)).commitWork();
    }

    @isTest
    static void whenCheckOnlineAgentsForBotActionWithNoAgentsTest() {

        Map<String, Id> skillNameToIdMap = new Map<String, Id>();
        for (Skill skill : SkillSelector.newInstance().selectAll()) {
            skillNameToIdMap.put(skill.DeveloperName, skill.Id);
        }

        fflib_ApexMocks mocks = new fflib_ApexMocks();
        LiveChatTranscriptSelector lctSelectorMock = (LiveChatTranscriptSelector) mocks.mock(LiveChatTranscriptSelector.class);
        PendingServiceRoutingSelector psrSelectorMock = (PendingServiceRoutingSelector) mocks.mock(PendingServiceRoutingSelector.class);
        ServiceResourceSkillSelector srsSelectorMock = (ServiceResourceSkillSelector) mocks.mock(ServiceResourceSkillSelector.class);
        ServiceChannelStatusSelector scsSelectorMock = (ServiceChannelStatusSelector) mocks.mock(ServiceChannelStatusSelector.class);
        UserServicePresenceSelector uspSelectorMock = (UserServicePresenceSelector) mocks.mock(UserServicePresenceSelector.class);
        AgentWorkSelector awSelectorMock = (AgentWorkSelector) mocks.mock(AgentWorkSelector.class);

        mocks.startStubbing();

        LiveChatTranscript testTranscript = new LiveChatTranscript(
            Id = fflib_IDGenerator.generate(LiveChatTranscript.SObjectType),
            Skills__c = 'DACH_English'
        );

        List<LiveChatTranscript> liveChatTrascripts = new List<LiveChatTranscript>();
        liveChatTrascripts.add(testTranscript);

        mocks.when(lctSelectorMock.sObjectType()).thenReturn(LiveChatTranscript.SObjectType);
        mocks.when(lctSelectorMock.selectByIdWithLiveChatButton(new Set<Id>{testTranscript.Id})).thenReturn(liveChatTrascripts);
        mocks.when(lctSelectorMock.selectBySkillsAndStatusFromLast24Hours(new List<String>{'DACH_English'}, 'Waiting')).thenReturn(liveChatTrascripts);

        mocks.when(psrSelectorMock.sObjectType()).thenReturn(PendingServiceRouting.SObjectType);
        mocks.when(psrSelectorMock.selectByWorkItemIdTransferredAndNotPushed(new Set<Id>{testTranscript.Id})).thenReturn(new List<PendingServiceRouting>());
        
        mocks.when(srsSelectorMock.sObjectType()).thenReturn(ServiceResourceSkill.SObjectType);
        mocks.when(srsSelectorMock.selectBySkillIds(new Set<Id>{skillNameToIdMap.get('DACH_English')})).thenReturn(new List<ServiceResourceSkill>());

        mocks.when(scsSelectorMock.sObjectType()).thenReturn(ServiceChannelStatus.SObjectType);
        mocks.when(scsSelectorMock.selectByRelatedServiceChannelEntity('LiveChatTranscript')).thenReturn(new List<ServiceChannelStatus>());

        mocks.when(uspSelectorMock.sObjectType()).thenReturn(UserServicePresence.SObjectType);
        mocks.when(uspSelectorMock.selectOnlineAgentsByServicePresenceStatusAndUsers(new Set<Id>(), new Set<Id>())).thenReturn(new List<UserServicePresence>());

        mocks.when(awSelectorMock.sObjectType()).thenReturn(AgentWork.SObjectType);
        mocks.when(awSelectorMock.selectOpenedAssignedWork(new Set<Id>())).thenReturn(new List<AgentWork>());

        mocks.stopStubbing();

        Application.Selector.setMock(lctSelectorMock);
        Application.Selector.setMock(psrSelectorMock);
        Application.Selector.setMock(srsSelectorMock);
        Application.Selector.setMock(scsSelectorMock);
        Application.Selector.setMock(uspSelectorMock);
        Application.Selector.setMock(awSelectorMock);

        BotCheckIfAgentOnlineHandler.BotInput botInput = new BotCheckIfAgentOnlineHandler.BotInput();
        botInput.langCode = 'en-GB';
        botInput.countryCode = 'de';
        botInput.churn = 'false';
        botInput.isFirstCheck = 'false';
        botInput.liveChatTranscriptId = testTranscript.Id;

        List<BotCheckIfAgentOnlineHandler.BotOutput> botOutput = ChatBotService.newInstance().checkIfAgentOnline(new List<BotCheckIfAgentOnlineHandler.BotInput>{botInput});
        system.assertEquals('false', botOutput[0].agentsAvailable);
        system.assertEquals('false', botOutput[0].transferToAgent);
    }

    @isTest
    static void whenCheckOnlineAgentsForBotActionWithAgentOnlineTest() {

        Map<String, Id> skillNameToIdMap = new Map<String, Id>();
        for (Skill skill : SkillSelector.newInstance().selectAll()) {
            skillNameToIdMap.put(skill.DeveloperName, skill.Id);
        }

        fflib_ApexMocks mocks = new fflib_ApexMocks();
        LiveChatTranscriptSelector lctSelectorMock = (LiveChatTranscriptSelector) mocks.mock(LiveChatTranscriptSelector.class);
        PendingServiceRoutingSelector psrSelectorMock = (PendingServiceRoutingSelector) mocks.mock(PendingServiceRoutingSelector.class);
        ServiceResourceSkillSelector srsSelectorMock = (ServiceResourceSkillSelector) mocks.mock(ServiceResourceSkillSelector.class);
        ServiceChannelStatusSelector scsSelectorMock = (ServiceChannelStatusSelector) mocks.mock(ServiceChannelStatusSelector.class);
        UserServicePresenceSelector uspSelectorMock = (UserServicePresenceSelector) mocks.mock(UserServicePresenceSelector.class);
        AgentWorkSelector awSelectorMock = (AgentWorkSelector) mocks.mock(AgentWorkSelector.class);

        mocks.startStubbing();

        LiveChatTranscript testTranscript = new LiveChatTranscript(
            Id = fflib_IDGenerator.generate(LiveChatTranscript.SObjectType),
            Skills__c = 'DACH_English'
        );

        List<LiveChatTranscript> liveChatTrascripts = new List<LiveChatTranscript>();
        liveChatTrascripts.add(testTranscript);

        mocks.when(lctSelectorMock.sObjectType()).thenReturn(LiveChatTranscript.SObjectType);
        mocks.when(lctSelectorMock.selectByIdWithLiveChatButton(new Set<Id>{testTranscript.Id})).thenReturn(new List<LiveChatTranscript>{testTranscript});
        mocks.when(lctSelectorMock.selectBySkillsAndStatusFromLast24Hours(new List<String>{'DACH_English'}, 'Waiting')).thenReturn(liveChatTrascripts);

        mocks.when(psrSelectorMock.sObjectType()).thenReturn(PendingServiceRouting.SObjectType);
        mocks.when(psrSelectorMock.selectByWorkItemIdTransferredAndNotPushed(new Set<Id>{testTranscript.Id})).thenReturn(new List<PendingServiceRouting>());
        
        User testUser = new User(
            Id = fflib_IDGenerator.generate(User.SObjectType)
        );

        ServiceResource sr = new ServiceResource(
            Id = fflib_IDGenerator.generate(ServiceResource.SObjectType),
            RelatedRecordId = testUser.Id
        );

        ServiceResourceSkill srs = new ServiceResourceSkill(
            Id = fflib_IDGenerator.generate(ServiceResourceSkill.SObjectType),
            SkillId = skillNameToIdMap.get('DACH_English'),
            ServiceResourceId = sr.Id,
            ServiceResource = sr
        );
        
        mocks.when(srsSelectorMock.sObjectType()).thenReturn(ServiceResourceSkill.SObjectType);
        mocks.when(srsSelectorMock.selectBySkillIds(new Set<Id>{skillNameToIdMap.get('DACH_English')})).thenReturn(new List<ServiceResourceSkill>{srs});

        ServiceChannel testServiceChannel = new ServiceChannel(
            Id = fflib_IDGenerator.generate(ServiceChannel.SObjectType),
            RelatedEntity = 'LiveChatTranscript'
        );

        ServiceChannelStatus testServiceChannelStatus = new ServiceChannelStatus(
            ServicePresenceStatusId = fflib_IDGenerator.generate(ServiceChannelStatus.SObjectType),
            ServiceChannelId = testServiceChannel.Id,
            ServiceChannel = testServiceChannel
        );

        mocks.when(scsSelectorMock.sObjectType()).thenReturn(ServiceChannelStatus.SObjectType);
        mocks.when(scsSelectorMock.selectByRelatedServiceChannelEntity('LiveChatTranscript')).thenReturn(new List<ServiceChannelStatus>{testServiceChannelStatus});

        UserServicePresence usp = new UserServicePresence(
            Id = fflib_IDGenerator.generate(UserServicePresence.SObjectType),
            ServicePresenceStatusId = testServiceChannelStatus.ServicePresenceStatusId,
            UserId = testUser.Id
        );
        
        mocks.when(uspSelectorMock.sObjectType()).thenReturn(UserServicePresence.SObjectType);
        mocks.when(uspSelectorMock.selectOnlineAgentsByServicePresenceStatusAndUsers(new Set<Id>{testServiceChannelStatus.ServicePresenceStatusId}, new Set<Id>{testUser.Id})).thenReturn(new List<UserServicePresence>{usp});

        AgentWork testAgentWork = new AgentWork(
            Id = fflib_IDGenerator.generate(AgentWork.SObjectType),
            CapacityWeight = 0,
            UserId = testUser.Id
        );

        mocks.when(awSelectorMock.sObjectType()).thenReturn(AgentWork.SObjectType);
        mocks.when(awSelectorMock.selectOpenedAssignedWork(new Set<Id>{usp.UserId})).thenReturn(new List<AgentWork>{testAgentWork});

        mocks.stopStubbing();

        Application.Selector.setMock(lctSelectorMock);
        Application.Selector.setMock(psrSelectorMock);
        Application.Selector.setMock(srsSelectorMock);
        Application.Selector.setMock(scsSelectorMock);
        Application.Selector.setMock(uspSelectorMock);
        Application.Selector.setMock(awSelectorMock);

        BotCheckIfAgentOnlineHandler.BotInput botInput = new BotCheckIfAgentOnlineHandler.BotInput();
        botInput.langCode = 'en-GB';
        botInput.countryCode = 'de';
        botInput.churn = 'false';
        botInput.isFirstCheck = 'false';
        botInput.liveChatTranscriptId = testTranscript.Id;

        List<BotCheckIfAgentOnlineHandler.BotOutput> botOutput = ChatBotService.newInstance().checkIfAgentOnline(new List<BotCheckIfAgentOnlineHandler.BotInput>{botInput});
        system.assertEquals('true', botOutput[0].agentsAvailable);
        system.assertEquals('true', botOutput[0].transferToAgent);
    }

    @isTest
    static void whenCheckOnlineAgentsForBotActionWithAgentOnlineWithWorkTest() {

        Map<String, Id> skillNameToIdMap = new Map<String, Id>();
        for (Skill skill : SkillSelector.newInstance().selectAll()) {
            skillNameToIdMap.put(skill.DeveloperName, skill.Id);
        }

        fflib_ApexMocks mocks = new fflib_ApexMocks();
        LiveChatTranscriptSelector lctSelectorMock = (LiveChatTranscriptSelector) mocks.mock(LiveChatTranscriptSelector.class);
        PendingServiceRoutingSelector psrSelectorMock = (PendingServiceRoutingSelector) mocks.mock(PendingServiceRoutingSelector.class);
        ServiceResourceSkillSelector srsSelectorMock = (ServiceResourceSkillSelector) mocks.mock(ServiceResourceSkillSelector.class);
        ServiceChannelStatusSelector scsSelectorMock = (ServiceChannelStatusSelector) mocks.mock(ServiceChannelStatusSelector.class);
        UserServicePresenceSelector uspSelectorMock = (UserServicePresenceSelector) mocks.mock(UserServicePresenceSelector.class);
        AgentWorkSelector awSelectorMock = (AgentWorkSelector) mocks.mock(AgentWorkSelector.class);

        mocks.startStubbing();

        LiveChatTranscript testTranscript = new LiveChatTranscript(
            Id = fflib_IDGenerator.generate(LiveChatTranscript.SObjectType),
            Skills__c = 'DACH_English'
        );

        List<LiveChatTranscript> liveChatTrascripts = new List<LiveChatTranscript>();
        liveChatTrascripts.add(testTranscript);

        ServiceChannel testServiceChannel = new ServiceChannel(
            Id = fflib_IDGenerator.generate(ServiceChannel.SObjectType),
            RelatedEntity = 'LiveChatTranscript'
        );

        mocks.when(lctSelectorMock.sObjectType()).thenReturn(LiveChatTranscript.SObjectType);
        mocks.when(lctSelectorMock.selectByIdWithLiveChatButton(new Set<Id>{testTranscript.Id})).thenReturn(new List<LiveChatTranscript>{testTranscript});
        mocks.when(lctSelectorMock.selectBySkillsAndStatusFromLast24Hours(new List<String>{'DACH_English'}, 'Waiting')).thenReturn(liveChatTrascripts);

        PendingServiceRouting psr = new PendingServiceRouting(
            WorkItemId = testTranscript.Id,
            CapacityWeight = 3,
            IsReadyForRouting = true,
            ServiceChannelId = testServiceChannel.Id
        );

        mocks.when(psrSelectorMock.sObjectType()).thenReturn(PendingServiceRouting.SObjectType);
        mocks.when(psrSelectorMock.selectByWorkItemIdTransferredAndNotPushed(new Set<Id>{testTranscript.Id})).thenReturn(new List<PendingServiceRouting>{psr});
        
        User testUser = new User(
            Id = fflib_IDGenerator.generate(User.SObjectType)
        );

        ServiceResource sr = new ServiceResource(
            Id = fflib_IDGenerator.generate(ServiceResource.SObjectType),
            RelatedRecordId = testUser.Id
        );

        ServiceResourceSkill srs = new ServiceResourceSkill(
            Id = fflib_IDGenerator.generate(ServiceResourceSkill.SObjectType),
            SkillId = skillNameToIdMap.get('DACH_English'),
            ServiceResourceId = sr.Id,
            ServiceResource = sr
        );
        
        mocks.when(srsSelectorMock.sObjectType()).thenReturn(ServiceResourceSkill.SObjectType);
        mocks.when(srsSelectorMock.selectBySkillIds(new Set<Id>{skillNameToIdMap.get('DACH_English')})).thenReturn(new List<ServiceResourceSkill>{srs});

        ServiceChannelStatus testServiceChannelStatus = new ServiceChannelStatus(
            ServicePresenceStatusId = fflib_IDGenerator.generate(ServiceChannelStatus.SObjectType),
            ServiceChannelId = testServiceChannel.Id,
            ServiceChannel = testServiceChannel
        );

        mocks.when(scsSelectorMock.sObjectType()).thenReturn(ServiceChannelStatus.SObjectType);
        mocks.when(scsSelectorMock.selectByRelatedServiceChannelEntity('LiveChatTranscript')).thenReturn(new List<ServiceChannelStatus>{testServiceChannelStatus});

        UserServicePresence usp = new UserServicePresence(
            Id = fflib_IDGenerator.generate(UserServicePresence.SObjectType),
            ServicePresenceStatusId = testServiceChannelStatus.ServicePresenceStatusId,
            UserId = testUser.Id
        );
        
        mocks.when(uspSelectorMock.sObjectType()).thenReturn(UserServicePresence.SObjectType);
        mocks.when(uspSelectorMock.selectOnlineAgentsByServicePresenceStatusAndUsers(new Set<Id>{testServiceChannelStatus.ServicePresenceStatusId}, new Set<Id>{testUser.Id})).thenReturn(new List<UserServicePresence>{usp});

        AgentWork testAgentWork = new AgentWork(
            Id = fflib_IDGenerator.generate(AgentWork.SObjectType),
            CapacityWeight = 0,
            UserId = testUser.Id
        );

        mocks.when(awSelectorMock.sObjectType()).thenReturn(AgentWork.SObjectType);
        mocks.when(awSelectorMock.selectOpenedAssignedWork(new Set<Id>{usp.UserId})).thenReturn(new List<AgentWork>{testAgentWork});

        mocks.stopStubbing();

        Application.Selector.setMock(lctSelectorMock);
        Application.Selector.setMock(psrSelectorMock);
        Application.Selector.setMock(srsSelectorMock);
        Application.Selector.setMock(scsSelectorMock);
        Application.Selector.setMock(uspSelectorMock);
        Application.Selector.setMock(awSelectorMock);

        BotCheckIfAgentOnlineHandler.BotInput botInput = new BotCheckIfAgentOnlineHandler.BotInput();
        botInput.langCode = 'en-GB';
        botInput.countryCode = 'de';
        botInput.churn = 'false';
        botInput.isFirstCheck = 'false';
        botInput.liveChatTranscriptId = testTranscript.Id;

        List<BotCheckIfAgentOnlineHandler.BotOutput> botOutput = ChatBotService.newInstance().checkIfAgentOnline(new List<BotCheckIfAgentOnlineHandler.BotInput>{botInput});
        system.assertEquals('true', botOutput[0].agentsAvailable);
        system.assertEquals('true', botOutput[0].transferToAgent);
    }

    @isTest
    static void whenCheckOnlineAgentsForBotActionWithAgentOnlineWhenOverloadedTest() {

        Map<String, Id> skillNameToIdMap = new Map<String, Id>();
        for (Skill skill : SkillSelector.newInstance().selectAll()) {
            skillNameToIdMap.put(skill.DeveloperName, skill.Id);
        }

        fflib_ApexMocks mocks = new fflib_ApexMocks();
        LiveChatTranscriptSelector lctSelectorMock = (LiveChatTranscriptSelector) mocks.mock(LiveChatTranscriptSelector.class);
        PendingServiceRoutingSelector psrSelectorMock = (PendingServiceRoutingSelector) mocks.mock(PendingServiceRoutingSelector.class);
        ServiceResourceSkillSelector srsSelectorMock = (ServiceResourceSkillSelector) mocks.mock(ServiceResourceSkillSelector.class);
        ServiceChannelStatusSelector scsSelectorMock = (ServiceChannelStatusSelector) mocks.mock(ServiceChannelStatusSelector.class);
        UserServicePresenceSelector uspSelectorMock = (UserServicePresenceSelector) mocks.mock(UserServicePresenceSelector.class);
        AgentWorkSelector awSelectorMock = (AgentWorkSelector) mocks.mock(AgentWorkSelector.class);

        mocks.startStubbing();

        LiveChatTranscript testTranscript = new LiveChatTranscript(
            Id = fflib_IDGenerator.generate(LiveChatTranscript.SObjectType),
            Skills__c = 'DACH_English'
        );

        LiveChatTranscript testTranscript2 = new LiveChatTranscript(
            Id = fflib_IDGenerator.generate(LiveChatTranscript.SObjectType),
            Skills__c = 'DACH_English'
        );

        List<LiveChatTranscript> liveChatTrascripts = new List<LiveChatTranscript>();
        liveChatTrascripts.add(testTranscript);
        liveChatTrascripts.add(testTranscript2);

        ServiceChannel testServiceChannel = new ServiceChannel(
            Id = fflib_IDGenerator.generate(ServiceChannel.SObjectType),
            RelatedEntity = 'LiveChatTranscript'
        );

        mocks.when(lctSelectorMock.sObjectType()).thenReturn(LiveChatTranscript.SObjectType);
        mocks.when(lctSelectorMock.selectByIdWithLiveChatButton(new Set<Id>{testTranscript.Id})).thenReturn(new List<LiveChatTranscript>{testTranscript});
        mocks.when(lctSelectorMock.selectBySkillsAndStatusFromLast24Hours(new List<String>{'DACH_English'}, 'Waiting')).thenReturn(liveChatTrascripts);

        PendingServiceRouting psr = new PendingServiceRouting(
            WorkItemId = testTranscript.Id,
            CapacityWeight = 3,
            IsReadyForRouting = true,
            ServiceChannelId = testServiceChannel.Id
        );

        PendingServiceRouting psr2 = new PendingServiceRouting(
            WorkItemId = testTranscript2.Id,
            CapacityWeight = 3,
            IsReadyForRouting = true,
            ServiceChannelId = testServiceChannel.Id
        );

        mocks.when(psrSelectorMock.sObjectType()).thenReturn(PendingServiceRouting.SObjectType);
        mocks.when(psrSelectorMock.selectByWorkItemIdTransferredAndNotPushed(new Set<Id>{testTranscript.Id, testTranscript2.Id})).thenReturn(new List<PendingServiceRouting>{psr,psr2});
        
        User testUser = new User(
            Id = fflib_IDGenerator.generate(User.SObjectType)
        );

        ServiceResource sr = new ServiceResource(
            Id = fflib_IDGenerator.generate(ServiceResource.SObjectType),
            RelatedRecordId = testUser.Id
        );

        ServiceResourceSkill srs = new ServiceResourceSkill(
            Id = fflib_IDGenerator.generate(ServiceResourceSkill.SObjectType),
            SkillId = skillNameToIdMap.get('DACH_English'),
            ServiceResourceId = sr.Id,
            ServiceResource = sr
        );
        
        mocks.when(srsSelectorMock.sObjectType()).thenReturn(ServiceResourceSkill.SObjectType);
        mocks.when(srsSelectorMock.selectBySkillIds(new Set<Id>{skillNameToIdMap.get('DACH_English')})).thenReturn(new List<ServiceResourceSkill>{srs});

        ServiceChannelStatus testServiceChannelStatus = new ServiceChannelStatus(
            ServicePresenceStatusId = fflib_IDGenerator.generate(ServiceChannelStatus.SObjectType),
            ServiceChannelId = testServiceChannel.Id,
            ServiceChannel = testServiceChannel
        );

        mocks.when(scsSelectorMock.sObjectType()).thenReturn(ServiceChannelStatus.SObjectType);
        mocks.when(scsSelectorMock.selectByRelatedServiceChannelEntity('LiveChatTranscript')).thenReturn(new List<ServiceChannelStatus>{testServiceChannelStatus});

        UserServicePresence usp = new UserServicePresence(
            Id = fflib_IDGenerator.generate(UserServicePresence.SObjectType),
            ServicePresenceStatusId = testServiceChannelStatus.ServicePresenceStatusId,
            UserId = testUser.Id
        );
        
        mocks.when(uspSelectorMock.sObjectType()).thenReturn(UserServicePresence.SObjectType);
        mocks.when(uspSelectorMock.selectOnlineAgentsByServicePresenceStatusAndUsers(new Set<Id>{testServiceChannelStatus.ServicePresenceStatusId}, new Set<Id>{testUser.Id})).thenReturn(new List<UserServicePresence>{usp});

        AgentWork testAgentWork = new AgentWork(
            Id = fflib_IDGenerator.generate(AgentWork.SObjectType),
            CapacityWeight = 6,
            UserId = testUser.Id
        );

        mocks.when(awSelectorMock.sObjectType()).thenReturn(AgentWork.SObjectType);
        mocks.when(awSelectorMock.selectOpenedAssignedWork(new Set<Id>{usp.UserId})).thenReturn(new List<AgentWork>{testAgentWork});

        mocks.stopStubbing();

        Application.Selector.setMock(lctSelectorMock);
        Application.Selector.setMock(psrSelectorMock);
        Application.Selector.setMock(srsSelectorMock);
        Application.Selector.setMock(scsSelectorMock);
        Application.Selector.setMock(uspSelectorMock);
        Application.Selector.setMock(awSelectorMock);

        BotCheckIfAgentOnlineHandler.BotInput botInput = new BotCheckIfAgentOnlineHandler.BotInput();
        botInput.langCode = 'en-GB';
        botInput.countryCode = 'de';
        botInput.churn = 'false';
        botInput.isFirstCheck = 'false';
        botInput.liveChatTranscriptId = testTranscript.Id;

        List<BotCheckIfAgentOnlineHandler.BotOutput> botOutput = ChatBotService.newInstance().checkIfAgentOnline(new List<BotCheckIfAgentOnlineHandler.BotInput>{botInput});
    
        system.assertEquals('true', botOutput[0].agentsAvailable);
        system.assertEquals(null, botOutput[0].transferToAgent);
        system.assertEquals('3', botOutput[0].customersInQueue);
    }

	@IsTest
    private static void userIntentMatchesWithContactUsOptions() {
        fflib_ApexMocks mocks = new fflib_ApexMocks();
        BotIntentCaseMappingSelector selectorMock = (BotIntentCaseMappingSelector) mocks.mock(BotIntentCaseMappingSelector.class);

        String intent = 'test intent';
        String type = 'test type';
        String subtype = 'test subtype';
        String subtype2 = 'test subtype2';

        // Given
        BotMapIntentToContactUsOptionHandler.BotInput botInput = new BotMapIntentToContactUsOptionHandler.BotInput();
        botInput.dialogName = intent;
        List<BotMapIntentToContactUsOptionHandler.BotInput> botInputs = new List<BotMapIntentToContactUsOptionHandler.BotInput>{BotInput};

        String mdtId = fflib_IDGenerator.generate(Bot_Intent_Case_Mapping__mdt.SObjectType);
        Map<String,Bot_Intent_Case_Mapping__mdt> testBotIntentCaseMappings = new Map<String,Bot_Intent_Case_Mapping__mdt> {
            mdtId => new Bot_Intent_Case_Mapping__mdt(
                Id = mdtId,
                Bot_Intent__c = intent,
                Type_Key__c = type,
                SubType_Key__c = subtype,
                SubType2_Key__c = subtype2
            )
        };

        mocks.startStubbing();
        mocks.when(selectorMock.sObjectType()).thenReturn(Bot_Intent_Case_Mapping__mdt.SObjectType);
        mocks.when(selectorMock.selectAll()).thenReturn(testBotIntentCaseMappings);
        mocks.stopStubbing();
        Application.Selector.setMock(selectorMock);

        // When
        List<BotMapIntentToContactUsOptionHandler.BotOutput> result = ChatBotService.newInstance().mapIntentToContactUsOption(BotInputs);

        // Then
        ((BotIntentCaseMappingSelector) mocks.verify(selectorMock, 1)).selectAll();
        System.assertEquals(1, result.size(), 'Case Intent should be mapped with a Contact Us option');
        System.assertEquals(type, result[0].typeKey, 'Type value is not correctly set');
        System.assertEquals(subtype, result[0].subtypeKey, 'Subtype value is not correctly set');
        System.assertEquals(subtype2, result[0].subtype2Key, 'Subtype2 value is not correctly set');
    }

    @IsTest
    private static void userIntentDoesNotMatchWithAnyContactUsOption() {
        fflib_ApexMocks mocks = new fflib_ApexMocks();
        BotIntentCaseMappingSelector selectorMock = (BotIntentCaseMappingSelector) mocks.mock(BotIntentCaseMappingSelector.class);

        String dialog = 'test dialog';
        String intent = 'test intent';
        String type = 'test type';
        String subtype = 'test subtype';
        String subtype2 = 'test subtype2';

        // Given
        BotMapIntentToContactUsOptionHandler.BotInput botInput = new BotMapIntentToContactUsOptionHandler.BotInput();
        botInput.dialogName = dialog;
        List<BotMapIntentToContactUsOptionHandler.BotInput> botInputs = new List<BotMapIntentToContactUsOptionHandler.BotInput>{BotInput};

        String mdtId = fflib_IDGenerator.generate(Bot_Intent_Case_Mapping__mdt.SObjectType);
        Map<String,Bot_Intent_Case_Mapping__mdt> testBotIntentCaseMappings = new Map<String,Bot_Intent_Case_Mapping__mdt> {
            mdtId => new Bot_Intent_Case_Mapping__mdt(
                Id = mdtId,
                Bot_Intent__c = intent,
                Type_Key__c = type,
                SubType_Key__c = subtype,
                SubType2_Key__c = subtype2
            )
        };

        mocks.startStubbing();
        mocks.when(selectorMock.sObjectType()).thenReturn(Bot_Intent_Case_Mapping__mdt.SObjectType);
        mocks.when(selectorMock.selectAll()).thenReturn(testBotIntentCaseMappings);
        mocks.stopStubbing();
        Application.Selector.setMock(selectorMock);

        // When
        List<BotMapIntentToContactUsOptionHandler.BotOutput> result = ChatBotService.newInstance().mapIntentToContactUsOption(BotInputs);

        // Then
        ((BotIntentCaseMappingSelector) mocks.verify(selectorMock, 1)).selectAll();
        System.assertEquals(0, result.size(), 'Case Intent should not be mapped with any Contact Us option');
    }

    @IsTest
    static void shouldUpdateDialogInstancesOnDialogCompletion() {
        fflib_ApexMocks mocks = new fflib_ApexMocks();

        fflib_ISObjectUnitOfWork uowMock = (fflib_ISObjectUnitOfWork) mocks.mock(fflib_ISObjectUnitOfWork.class);
        LiveChatTranscript testTranscript = new LiveChatTranscript(
                Id = fflib_IDGenerator.generate(LiveChatTranscript.SObjectType)
        );

        Bot_Dialog_Instance__c botInstance = new Bot_Dialog_Instance__c(
                Id = fflib_IDGenerator.generate(Bot_Dialog_Instance__c.SObjectType),
                RecordTypeId = Schema.SObjectType.Bot_Dialog_Instance__c.getRecordTypeInfosByName()
                        .get(ChatBotService.RECORD_TYPE_NAME_DIALOG).getRecordTypeId(),
                Chat_Transcript__c = testTranscript.Id,
                Dialog_Name__c = 'testSolution',
                Goal_Name__c = 'testGoal',
                Type__c = 'Rating',
                Status__c = ChatBotService.STATUS_NAME_REDIRECTED
        );

        BotDialogCompletionHandler.DialogCompletionOutput botOutput = new BotDialogCompletionHandler.DialogCompletionOutput();
        botOutput.sCurrentDialog = 'testDialog';
        botOutput.bRating = true;

        BotDialogCompletionHandler.DialogCompletionWrapper dialogCompletionWrapper = new BotDialogCompletionHandler.DialogCompletionWrapper();
        dialogCompletionWrapper.sLastCustomerInput = 'Test';
        dialogCompletionWrapper.systemLastCustomerInput = 'TESTing';
        dialogCompletionWrapper.rating = true;


        Map<String, BotDialogCompletionHandler.DialogCompletionWrapper> mapCompletionWrappersByStrings = new Map<String, BotDialogCompletionHandler.DialogCompletionWrapper>();
        mapCompletionWrappersByStrings.put(botInstance.Dialog_Name__c, dialogCompletionWrapper);

        Application.UnitOfWork.setMock(uowMock);

        ChatBotService.newInstance().updateDialogInstancesOnDialogCompletion(new List<Bot_Dialog_Instance__c>{botInstance}, mapCompletionWrappersByStrings);

        ((fflib_ISObjectUnitOfWork) mocks.verify(uowMock, 1)).commitWork();
    }
*/
}