src/objects/Bot_Dialog__c.object
<CustomObject>
    <fields>
        <fullName>Bot_Name__c</fullName>
        <description>API name of the Bot that this Dialog belongs to.</description>
        <label>Bot Name</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Dialog_Name__c</fullName>
        <label>Dialog Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Goal_Name__c</fullName>
        <label>Goal Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Solution</fullName>
                </value>
                <value>
                    <fullName>Intermediate</fullName>
                </value>
                <value>
                    <fullName>Escalate</fullName>
                </value>
                <value>
                    <fullName>Navigation</fullName>
                </value>
                <value>
                    <fullName>Next</fullName>
                </value>
                <value>
                    <fullName>Rating</fullName>
                </value>
                <value>
                    <fullName>Back</fullName>
                </value>
                <value>
                    <fullName>Confusion</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Bot Dialog</label>
    <nameField>
        <displayFormat>BD-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bot Dialogs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/BotDialogSelector.cls
public inherited sharing class BotDialogSelector extends fflib_SObjectSelector {
    public static BotDialogSelector newInstance() {
        return (BotDialogSelector) Application.Selector.newInstance(Bot_Dialog__c.SObjectType);
    }

    public List<Schema.SObjectField> getSObjectFieldList() {
        return new List<Schema.SObjectField>{
                Bot_Dialog__c.Dialog_Name__c,
                Bot_Dialog__c.Goal_Name__c,
                Bot_Dialog__c.Type__c,
                Bot_Dialog__c.Bot_Name__c
        };
    }

    public List<Bot_Dialog__c> selectById(Set<Id> idSet) {
        return (List<Bot_Dialog__c>) selectSObjectsById(idSet);
    }

    public List<Bot_Dialog__c> selectByDialogName(Set<String> dialogNames) {
        fflib_QueryFactory query = newQueryFactory();
        query.setCondition('Dialog_Name__c IN :dialogNames');
        return (List<Bot_Dialog__c>) Database.query(query.toSOQL());
    }

    public Schema.SObjectType getSObjectType() {
        return Bot_Dialog__c.SObjectType;
    }

}