src/objects/Bot_Dialog_Instance__c.object
<CustomObject>
    <fields>
        <fullName>Chat_Transcript__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Chat Transcript</label>
        <referenceTo>LiveChatTranscript</referenceTo>
        <relationshipLabel>Bot Dialog Instances</relationshipLabel>
        <relationshipName>Bot_Dialog_Instances</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Dialog_Name__c</fullName>
        <label>Dialog Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Goal_Name__c</fullName>
        <label>Goal Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Customer_Input__c</fullName>
        <label>Last Customer Input</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Step__c</fullName>
        <label>Last Step</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Rating__c</fullName>
        <label>Rating</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Success</fullName>
                </value>
                <value>
                    <fullName>Failure</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Abandoned</fullName>
                </value>
                <value>
                    <fullName>Back</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Escalated</fullName>
                </value>
                <value>
                    <fullName>Redirected</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <label>Bot Dialog Instance</label>
    <nameField>
        <displayFormat>BDI-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bot Dialog Instances</pluralLabel>
    <recordTypes>
        <fullName>Dialog</fullName>
        <active>true</active>
        <label>Dialog</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/BotDialogInstanceSelector.cls
public inherited sharing class BotDialogInstanceSelector extends fflib_SObjectSelector {
    public static BotDialogInstanceSelector newInstance() {
        return (BotDialogInstanceSelector) Application.Selector.newInstance(Bot_Dialog_Instance__c.SObjectType);
    }

    public List<Schema.SObjectField> getSObjectFieldList() {
        return new List<Schema.SObjectField>{
                Bot_Dialog_Instance__c.Name,
                Bot_Dialog_Instance__c.Dialog_Name__c,
                Bot_Dialog_Instance__c.Goal_Name__c,
                Bot_Dialog_Instance__c.Type__c,
                Bot_Dialog_Instance__c.Status__c,
                Bot_Dialog_Instance__c.CreatedDate,
                Bot_Dialog_Instance__c.Last_Customer_Input__c,
                Bot_Dialog_Instance__c.Chat_Transcript__c,
                Bot_Dialog_Instance__c.Rating__c,
                Bot_Dialog_Instance__c.Last_Step__c,
                Bot_Dialog_Instance__c.CreatedDate
        };
    }

    public List<Bot_Dialog_Instance__c> selectById(Set<Id> idSet) {
        return (List<Bot_Dialog_Instance__c>) selectSObjectsById(idSet);
    }

    public List<Bot_Dialog_Instance__c> selectByTranscriptId(Set<Id> transcriptIds) {
        fflib_QueryFactory query = newQueryFactory();
        query.setCondition('Chat_Transcript__c IN :transcriptIds AND RecordType.Name = \'Dialog\'');
        query.addOrdering(new fflib_QueryFactory.Ordering('Bot_Dialog_Instance__c', 'Id', fflib_QueryFactory.SortOrder.DESCENDING));
        return (List<Bot_Dialog_Instance__c>) Database.query(query.toSOQL());
    }

    public List<Bot_Dialog_Instance__c> selectByTranscriptIdAndDialogName(Set<Id> transcriptIds, Set<String> dialogNames) {
        fflib_QueryFactory query = newQueryFactory();
        query.setCondition('Chat_Transcript__c IN :transcriptIds AND Dialog_Name__c IN :dialogNames AND Status__c <> \'Completed\'');
        return (List<Bot_Dialog_Instance__c>) Database.query(query.toSOQL());
    }

    public Schema.SObjectType getSObjectType() {
        return Bot_Dialog_Instance__c.SObjectType;
    }
}