src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Sub_Type2__c</fullName>
        <label>Sub-Type2</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Sub_Type__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>How do I amend my order?</fullName>
                </value>
                <value>
                    <fullName>How do I access the &quot;My Account&quot; area?</fullName>
                </value>
                <value>
                    <fullName>Help with Error codes</fullName>
                </value>
                <value>
                    <fullName>How do I cancel my subscription?</fullName>
                </value>
                <value>
                    <fullName>How do I change my marketing preferences?</fullName>
                </value>
                <value>
                    <fullName>How do I change my password?</fullName>
                </value>
                <value>
                    <fullName>How do I change my payment method?</fullName>
                </value>
                <value>
                    <fullName>How do I change my personal details?</fullName>
                </value>
                <value>
                    <fullName>How do I change or update my payment method?</fullName>
                </value>
                <value>
                    <fullName>How do I install my DAZN TV device?</fullName>
                </value>
                <value>
                    <fullName>How do I order a new DAZN TV device</fullName>
                </value>
                <value>
                    <fullName>How do I sign in to DAZN for Business?</fullName>
                </value>
                <value>
                    <fullName>How do I sign up to DAZN for Business?</fullName>
                </value>
                <value>
                    <fullName>How do I track my order?</fullName>
                </value>
                <value>
                    <fullName>How do I use the DAZN TV device?</fullName>
                </value>
                <value>
                    <fullName>How do I view my bill?</fullName>
                </value>
                <value>
                    <fullName>I can&apos;t find the content I want to view</fullName>
                </value>
                <value>
                    <fullName>I can&apos;t pair my remote</fullName>
                </value>
                <value>
                    <fullName>I cannot sign in to DAZN for Business</fullName>
                </value>
                <value>
                    <fullName>I cannot sign in to the &quot;My Account&quot; area</fullName>
                </value>
                <value>
                    <fullName>I did not receive a password reset email</fullName>
                </value>
                <value>
                    <fullName>I forgot my email</fullName>
                </value>
                <value>
                    <fullName>I forgot my password</fullName>
                </value>
                <value>
                    <fullName>I have a blank screen</fullName>
                </value>
                <value>
                    <fullName>I have no audio</fullName>
                </value>
                <value>
                    <fullName>I have problems with my delivery</fullName>
                </value>
                <value>
                    <fullName>I was incorrectly charged</fullName>
                </value>
                <value>
                    <fullName>I&apos;m unable to sign up</fullName>
                </value>
                <value>
                    <fullName>I&apos;ve lost my remote</fullName>
                </value>
                <value>
                    <fullName>My DAZN App Doesn&apos;t Open</fullName>
                </value>
                <value>
                    <fullName>Test</fullName>
                    <isActive>false</isActive>
                    <label>Test</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Sub_Type__c</fullName>
        <description>Case sub-types, this field is dependent on case type field.</description>
        <label>Sub-Type</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Type</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>About DAZN for Business</fullName>
                </value>
                <value>
                    <fullName>STB Delivery &amp; installation</fullName>
                </value>
                <value>
                    <fullName>Creating a new account</fullName>
                </value>
                <value>
                    <fullName>Username and Password</fullName>
                </value>
                <value>
                    <fullName>Update my details</fullName>
                </value>
                <value>
                    <fullName>Remote Control Issues</fullName>
                </value>
                <value>
                    <fullName>Billing</fullName>
                </value>
                <value>
                    <fullName>Problems Watching</fullName>
                </value>
                <value>
                    <fullName>DAZN TV device issues</fullName>
                </value>
                <value>
                    <fullName>My Account</fullName>
                </value>
                <value>
                    <fullName>Abandoned Chat</fullName>
                </value>
                <value>
                    <fullName>Unable to classify</fullName>
                </value>
                <value>
                    <fullName>Missed Chat</fullName>
                </value>
                <value>
                    <fullName>About DAZN</fullName>
                    <isActive>false</isActive>
                    <label>About DAZN</label>
                </value>
                <value>
                    <fullName>Access to My Account</fullName>
                    <isActive>false</isActive>
                    <label>Access to My Account</label>
                </value>
                <value>
                    <fullName>Account Reactivation through SNL</fullName>
                    <isActive>false</isActive>
                    <label>Account Reactivation through SNL</label>
                </value>
                <value>
                    <fullName>Age Verification</fullName>
                    <isActive>false</isActive>
                    <label>Age Verification</label>
                </value>
                <value>
                    <fullName>App Feedback</fullName>
                    <isActive>false</isActive>
                    <label>App Feedback</label>
                </value>
                <value>
                    <fullName>App Installation &amp; Use</fullName>
                    <isActive>false</isActive>
                    <label>App Installation &amp; Use</label>
                </value>
                <value>
                    <fullName>App Issues</fullName>
                    <isActive>false</isActive>
                    <label>App Issues</label>
                </value>
                <value>
                    <fullName>App features</fullName>
                    <isActive>false</isActive>
                    <label>App features</label>
                </value>
                <value>
                    <fullName>BILDplus</fullName>
                    <isActive>false</isActive>
                    <label>BILDplus</label>
                </value>
                <value>
                    <fullName>Cancellation</fullName>
                    <isActive>false</isActive>
                    <label>Cancellation</label>
                </value>
                <value>
                    <fullName>Cancellation reasons</fullName>
                    <isActive>false</isActive>
                    <label>Cancellation reasons</label>
                </value>
                <value>
                    <fullName>Cancelling my account</fullName>
                    <isActive>false</isActive>
                    <label>Cancelling my account</label>
                </value>
                <value>
                    <fullName>Casting to another device</fullName>
                    <isActive>false</isActive>
                    <label>Casting to another device</label>
                </value>
                <value>
                    <fullName>Changing my subscription type</fullName>
                    <isActive>false</isActive>
                    <label>Changing my subscription type</label>
                </value>
                <value>
                    <fullName>Comment about marketing or adverts</fullName>
                    <isActive>false</isActive>
                    <label>Comment about marketing or adverts</label>
                </value>
                <value>
                    <fullName>Content Feedback</fullName>
                    <isActive>false</isActive>
                    <label>Content Feedback</label>
                </value>
                <value>
                    <fullName>Customer Service</fullName>
                    <isActive>false</isActive>
                    <label>Customer Service</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

src/objects/Contact_Us_SubType2_Option__c.object
<CustomObject>
    <fields>
        <fullName>SubType_Key__c</fullName>
        <label>SubType Key</label>
        <referenceTo>Contact_Us_SubType_Option__c</referenceTo>
        <relationshipLabel>ContactUs SubType2 Options</relationshipLabel>
        <relationshipName>Contact_Us_SubType2_Options</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>View__c</fullName>
        <label>View</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>ContactUs SubType2 Option</label>
    <nameField>
        <label>SubType2 Key</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ContactUs SubType2 Options</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Contact_Us_SubType_Option__c.object
<CustomObject>
    <fields>
        <fullName>Type_Key__c</fullName>
        <label>Type Key</label>
        <referenceTo>Contact_Us_Type_Option__c</referenceTo>
        <relationshipLabel>ContactUs SubType Options</relationshipLabel>
        <relationshipName>Contact_Us_SubType_Options</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>View__c</fullName>
        <label>View</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>ContactUs SubType Option</label>
    <nameField>
        <label>SubType Key</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ContactUs SubType Options</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Contact_Us_Type_Option__c.object
<CustomObject>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>AR</fullName>
                </value>
                <value>
                    <fullName>AT</fullName>
                </value>
                <value>
                    <fullName>BR</fullName>
                </value>
                <value>
                    <fullName>CA</fullName>
                </value>
                <value>
                    <fullName>CH</fullName>
                </value>
                <value>
                    <fullName>CL</fullName>
                </value>
                <value>
                    <fullName>CO</fullName>
                </value>
                <value>
                    <fullName>DE</fullName>
                </value>
                <value>
                    <fullName>ES</fullName>
                </value>
                <value>
                    <fullName>IT</fullName>
                </value>
                <value>
                    <fullName>JP</fullName>
                </value>
                <value>
                    <fullName>US</fullName>
                </value>
                <value>
                    <fullName>ZA</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Language__c</fullName>
        <label>Language</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>en</fullName>
                </value>
                <value>
                    <fullName>de</fullName>
                </value>
                <value>
                    <fullName>ja</fullName>
                </value>
                <value>
                    <fullName>fr</fullName>
                </value>
                <value>
                    <fullName>es</fullName>
                </value>
                <value>
                    <fullName>it</fullName>
                </value>
                <value>
                    <fullName>pt</fullName>
                </value>
                <value>
                    <fullName>en_ZA</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>View__c</fullName>
        <label>View</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>ContactUs Type Option</label>
    <nameField>
        <label>Type Key</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ContactUs Type Options</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ContactUsOptionServiceTest.cls
@IsTest
private class ContactUsOptionServiceTest {
    @IsTest
    static void callingServiceShouldCallSelectors() {
        // Create mocks
        fflib_ApexMocks mocks = new fflib_ApexMocks();
        CaseSelector caseSelectorMock = (CaseSelector) mocks.mock(CaseSelector.class);
        ContactUsTypeOptionSelector contactUsTypeOptionSelectorMock = (ContactUsTypeOptionSelector) mocks.mock(ContactUsTypeOptionSelector.class);
        ContactUsSubTypeOptionSelector contactUsSubTypeOptionSelectorMock = (ContactUsSubTypeOptionSelector) mocks.mock(ContactUsSubTypeOptionSelector.class);
        ContactUsSubType2OptionSelector contactUsSubType2OptionSelectorMock = (ContactUsSubType2OptionSelector) mocks.mock(ContactUsSubType2OptionSelector.class);

        // Given
        mocks.startStubbing();
        String userLanguage = UserInfo.getLanguage().substringBefore('_');
        String optionName = 'Test';
        List<Case> testCases = new List<Case> {
            new Case(
                Id = fflib_IDGenerator.generate(Case.SObjectType),
                Type = optionName,
                Sub_Type__c = optionName,
                Sub_Type2__c = optionName
            )
        };
        Set<Id> testCaseIds = new Map<Id, Case> (testCases).keySet();

        List<Contact_Us_Type_Option__c> testContactUsTypeOptions = new List<Contact_Us_Type_Option__c> {
            new Contact_Us_Type_Option__c(
                Name = optionName,
                View__c = optionName
            )
        };

        List<Contact_Us_SubType_Option__c> testContactUsSubTypeOptions = new List<Contact_Us_SubType_Option__c> {
            new Contact_Us_SubType_Option__c(
                Name = optionName,
                View__c = optionName
            )
        };

        List<Contact_Us_SubType2_Option__c> testContactUsSubType2Options = new List<Contact_Us_SubType2_Option__c> {
            new Contact_Us_SubType2_Option__c(
                Name = optionName,
                View__c = optionName
            )
        };
        ContactUsOptionService.TypeOptionWrapper tow = new ContactUsOptionService.TypeOptionWrapper();
        tow.type = testCases.get(0).Type;
        tow.subType = testCases.get(0).Sub_Type__c;
        tow.subType2 = testCases.get(0).Sub_Type2__c;
        mocks.when(caseSelectorMock.sObjectType()).thenReturn(Case.SObjectType);
        mocks.when(caseSelectorMock.selectById(new Set<Id> { testCases.get(0).Id })).thenReturn(testCases);
        mocks.when(contactUsTypeOptionSelectorMock.sObjectType()).thenReturn(Contact_Us_Type_Option__c.SObjectType);
        mocks.when(contactUsTypeOptionSelectorMock.selectByLanguage(userLanguage)).thenReturn(testContactUsTypeOptions);
        mocks.when(contactUsSubTypeOptionSelectorMock.sObjectType()).thenReturn(Contact_Us_SubType_Option__c.SObjectType);
        mocks.when(contactUsSubTypeOptionSelectorMock.selectByLanguageAndMasterOption(userLanguage, optionName)).thenReturn(testContactUsSubTypeOptions);
        mocks.when(contactUsSubType2OptionSelectorMock.sObjectType()).thenReturn(Contact_Us_SubType2_Option__c.SObjectType);
        mocks.when(contactUsSubType2OptionSelectorMock.selectByLanguageAndMasterOption(userLanguage, optionName)).thenReturn(testContactUsSubType2Options);
        mocks.stopStubbing();
        Application.Selector.setMock(caseSelectorMock);
        Application.Selector.setMock(contactUsTypeOptionSelectorMock);
        Application.Selector.setMock(contactUsSubTypeOptionSelectorMock);
        Application.Selector.setMock(contactUsSubType2OptionSelectorMock);

        // When
        ContactUsOptionService.newInstance().getContactUsOptions(testCases.get(0).Id);

        // Then
        ((CaseSelector) mocks.verify(caseSelectorMock, 1)).selectById(testCaseIds);
        ((ContactUsTypeOptionSelector) mocks.verify(contactUsTypeOptionSelectorMock)).selectByLanguage(userLanguage);
        ((ContactUsSubTypeOptionSelector) mocks.verify(contactUsSubTypeOptionSelectorMock)).selectByLanguageAndMasterOption(userLanguage, optionName);
        ((ContactUsSubType2OptionSelector) mocks.verify(contactUsSubType2OptionSelectorMock)).selectByLanguageAndMasterOption(userLanguage, optionName);
    }

    @IsTest
    static void callingServiceForBotShouldCallSelectorsAndReturnRecords() {
        // Create mocks
        fflib_ApexMocks mocks = new fflib_ApexMocks();
        ContactUsTypeOptionSelector contactUsTypeOptionSelectorMock = (ContactUsTypeOptionSelector) mocks.mock(ContactUsTypeOptionSelector.class);
        ContactUsSubTypeOptionSelector contactUsSubTypeOptionSelectorMock = (ContactUsSubTypeOptionSelector) mocks.mock(ContactUsSubTypeOptionSelector.class);
        ContactUsSubType2OptionSelector contactUsSubType2OptionSelectorMock = (ContactUsSubType2OptionSelector) mocks.mock(ContactUsSubType2OptionSelector.class);

        // Given
        mocks.startStubbing();
        String language = 'en';
        String country = 'US';
        String optionTypeName = 'Test';
        String optionSubTypeName = 'SubTest';
        String optionSubType2Name = 'SubTest2';

        List<String> languages = new List<String>{language};
        Set<String> languagesSet = new Set<String>(languages);
        Set<String> countries = new Set<String>{country};

        String contactUsTypeOptionId = fflib_IDGenerator.generate(Contact_Us_Type_Option__c.SObjectType);
        String contactUsSubTypeOptionId = fflib_IDGenerator.generate(Contact_Us_SubType_Option__c.SObjectType);
        String contactUsSubType2OptionId = fflib_IDGenerator.generate(Contact_Us_SubType2_Option__c.SObjectType);

        List<String> typeNames = new List<String>{optionTypeName};
        List<String> subTypeNames = new List<String>{optionSubTypeName};

        List<Contact_Us_Type_Option__c> testContactUsTypeOptions = new List<Contact_Us_Type_Option__c> {
            new Contact_Us_Type_Option__c(
                Id = contactUsTypeOptionId,
                Language__c = language,
                Country__c = country,
                Name = optionTypeName,
                View__c = optionTypeName
            )
        };

        List<Contact_Us_SubType_Option__c> testContactUsSubTypeOptions = new List<Contact_Us_SubType_Option__c> {
            new Contact_Us_SubType_Option__c(
                Id = contactUsSubTypeOptionId,
                Type_Key__c = contactUsTypeOptionId,
                Type_Key__r = testContactUsTypeOptions.get(0),
                Name = optionSubTypeName,
                View__c = optionSubTypeName
            )
        };

        List<Contact_Us_SubType2_Option__c> testContactUsSubType2Options = new List<Contact_Us_SubType2_Option__c> {
            new Contact_Us_SubType2_Option__c(
                Id = contactUsSubType2OptionId,
                SubType_Key__c = contactUsSubTypeOptionId,
                SubType_Key__r = testContactUsSubTypeOptions.get(0),
                Name = optionSubType2Name,
                View__c = optionSubType2Name
            )
        };

        BotGetContactUsOptionsHandler.BotInput typeBotInput = new BotGetContactUsOptionsHandler.BotInput();
        typeBotInput.language = language;
        typeBotInput.country = country;
        BotGetContactUsOptionsHandler.BotInput subTypeBotInput = new BotGetContactUsOptionsHandler.BotInput();
        subTypeBotInput.masterTypeOptionName = testContactUsTypeOptions.get(0).Name;
        subTypeBotInput.language = language;
        BotGetContactUsOptionsHandler.BotInput subType2BotInput = new BotGetContactUsOptionsHandler.BotInput();
        subType2BotInput.masterSubTypeOptionName = testContactUsSubTypeOptions.get(0).Name;
        subType2BotInput.language = language;

        List<BotGetContactUsOptionsHandler.BotInput> botInputs = new List<BotGetContactUsOptionsHandler.BotInput> {
            typeBotInput, subTypeBotInput, subType2BotInput
        };

        mocks.when(contactUsTypeOptionSelectorMock.sObjectType()).thenReturn(Contact_Us_Type_Option__c.SObjectType);
        mocks.when(contactUsTypeOptionSelectorMock.selectByLanguageAndCountry(languagesSet, countries)).thenReturn(testContactUsTypeOptions);
        mocks.when(contactUsSubTypeOptionSelectorMock.sObjectType()).thenReturn(Contact_Us_SubType_Option__c.SObjectType);
        mocks.when(contactUsSubTypeOptionSelectorMock.selectByMasterOptionNameAndLanguage(languages, typeNames)).thenReturn(testContactUsSubTypeOptions);
        mocks.when(contactUsSubType2OptionSelectorMock.sObjectType()).thenReturn(Contact_Us_SubType2_Option__c.SObjectType);
        mocks.when(contactUsSubType2OptionSelectorMock.selectByMasterOptionNameAndLanguage(languages, subTypeNames)).thenReturn(testContactUsSubType2Options);
        mocks.stopStubbing();
        Application.Selector.setMock(contactUsTypeOptionSelectorMock);
        Application.Selector.setMock(contactUsSubTypeOptionSelectorMock);
        Application.Selector.setMock(contactUsSubType2OptionSelectorMock);

        // When
        List<List<SObject>> botResults = ContactUsOptionService.newInstance().getContactUsOptionsForBot(botInputs);

        // Then
        ((ContactUsTypeOptionSelector) mocks.verify(contactUsTypeOptionSelectorMock, 1)).selectByLanguageAndCountry(languagesSet, countries);
        ((ContactUsSubTypeOptionSelector) mocks.verify(contactUsSubTypeOptionSelectorMock, 1)).selectByMasterOptionNameAndLanguage(languages, typeNames);
        ((ContactUsSubType2OptionSelector) mocks.verify(contactUsSubType2OptionSelectorMock, 1)).selectByMasterOptionNameAndLanguage(languages, subTypeNames);
        System.assertEquals(contactUsTypeOptionId, botResults.get(0).get(0).Id);
        System.assertEquals(contactUsSubTypeOptionId, botResults.get(1).get(0).Id);
        System.assertEquals(contactUsSubType2OptionId, botResults.get(2).get(0).Id);
    }
}