src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Sub_Type2__c</fullName>
        <label>Sub-Type2</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Sub_Type__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>How do I amend my order?</fullName>
                </value>
                <value>
                    <fullName>How do I access the &quot;My Account&quot; area?</fullName>
                </value>
                <value>
                    <fullName>Help with Error codes</fullName>
                </value>
                <value>
                    <fullName>How do I cancel my subscription?</fullName>
                </value>
                <value>
                    <fullName>How do I change my marketing preferences?</fullName>
                </value>
                <value>
                    <fullName>How do I change my password?</fullName>
                </value>
                <value>
                    <fullName>How do I change my payment method?</fullName>
                </value>
                <value>
                    <fullName>How do I change my personal details?</fullName>
                </value>
                <value>
                    <fullName>How do I change or update my payment method?</fullName>
                </value>
                <value>
                    <fullName>How do I install my DAZN TV device?</fullName>
                </value>
                <value>
                    <fullName>How do I order a new DAZN TV device</fullName>
                </value>
                <value>
                    <fullName>How do I sign in to DAZN for Business?</fullName>
                </value>
                <value>
                    <fullName>How do I sign up to DAZN for Business?</fullName>
                </value>
                <value>
                    <fullName>How do I track my order?</fullName>
                </value>
                <value>
                    <fullName>How do I use the DAZN TV device?</fullName>
                </value>
                <value>
                    <fullName>How do I view my bill?</fullName>
                </value>
                <value>
                    <fullName>I can&apos;t find the content I want to view</fullName>
                </value>
                <value>
                    <fullName>I can&apos;t pair my remote</fullName>
                </value>
                <value>
                    <fullName>I cannot sign in to DAZN for Business</fullName>
                </value>
                <value>
                    <fullName>I cannot sign in to the &quot;My Account&quot; area</fullName>
                </value>
                <value>
                    <fullName>I did not receive a password reset email</fullName>
                </value>
                <value>
                    <fullName>I forgot my email</fullName>
                </value>
                <value>
                    <fullName>I forgot my password</fullName>
                </value>
                <value>
                    <fullName>I have a blank screen</fullName>
                </value>
                <value>
                    <fullName>I have no audio</fullName>
                </value>
                <value>
                    <fullName>I have problems with my delivery</fullName>
                </value>
                <value>
                    <fullName>I was incorrectly charged</fullName>
                </value>
                <value>
                    <fullName>I&apos;m unable to sign up</fullName>
                </value>
                <value>
                    <fullName>I&apos;ve lost my remote</fullName>
                </value>
                <value>
                    <fullName>My DAZN App Doesn&apos;t Open</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Sub_Type__c</fullName>
        <description>Case sub-types, this field is dependent on case type field.</description>
        <label>Sub-Type</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Type</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>About DAZN for Business</fullName>
                </value>
                <value>
                    <fullName>STB Delivery &amp; installation</fullName>
                </value>
                <value>
                    <fullName>Creating a new account</fullName>
                </value>
                <value>
                    <fullName>Username and Password</fullName>
                </value>
                <value>
                    <fullName>Update my details</fullName>
                </value>
                <value>
                    <fullName>Remote Control Issues</fullName>
                </value>
                <value>
                    <fullName>Billing</fullName>
                </value>
                <value>
                    <fullName>Problems Watching</fullName>
                </value>
                <value>
                    <fullName>DAZN TV device issues</fullName>
                </value>
                <value>
                    <fullName>My Account</fullName>
                </value>
                <value>
                    <fullName>Abandoned Chat</fullName>
                </value>
                <value>
                    <fullName>Unable to classify</fullName>
                </value>
                <value>
                    <fullName>Missed Chat</fullName>
                </value>
                <value>
                    <fullName>About DAZN</fullName>
                    <isActive>false</isActive>
                    <label>About DAZN</label>
                </value>
                <value>
                    <fullName>Access to My Account</fullName>
                    <isActive>false</isActive>
                    <label>Access to My Account</label>
                </value>
                <value>
                    <fullName>Account Reactivation through SNL</fullName>
                    <isActive>false</isActive>
                    <label>Account Reactivation through SNL</label>
                </value>
                <value>
                    <fullName>Age Verification</fullName>
                    <isActive>false</isActive>
                    <label>Age Verification</label>
                </value>
                <value>
                    <fullName>App Feedback</fullName>
                    <isActive>false</isActive>
                    <label>App Feedback</label>
                </value>
                <value>
                    <fullName>App Installation &amp; Use</fullName>
                    <isActive>false</isActive>
                    <label>App Installation &amp; Use</label>
                </value>
                <value>
                    <fullName>App Issues</fullName>
                    <isActive>false</isActive>
                    <label>App Issues</label>
                </value>
                <value>
                    <fullName>App features</fullName>
                    <isActive>false</isActive>
                    <label>App features</label>
                </value>
                <value>
                    <fullName>BILDplus</fullName>
                    <isActive>false</isActive>
                    <label>BILDplus</label>
                </value>
                <value>
                    <fullName>Cancellation</fullName>
                    <isActive>false</isActive>
                    <label>Cancellation</label>
                </value>
                <value>
                    <fullName>Cancellation reasons</fullName>
                    <isActive>false</isActive>
                    <label>Cancellation reasons</label>
                </value>
                <value>
                    <fullName>Cancelling my account</fullName>
                    <isActive>false</isActive>
                    <label>Cancelling my account</label>
                </value>
                <value>
                    <fullName>Casting to another device</fullName>
                    <isActive>false</isActive>
                    <label>Casting to another device</label>
                </value>
                <value>
                    <fullName>Changing my subscription type</fullName>
                    <isActive>false</isActive>
                    <label>Changing my subscription type</label>
                </value>
                <value>
                    <fullName>Comment about marketing or adverts</fullName>
                    <isActive>false</isActive>
                    <label>Comment about marketing or adverts</label>
                </value>
                <value>
                    <fullName>Content Feedback</fullName>
                    <isActive>false</isActive>
                    <label>Content Feedback</label>
                </value>
                <value>
                    <fullName>Customer Service</fullName>
                    <isActive>false</isActive>
                    <label>Customer Service</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

src/objects/Contact_Us_SubType2_Option__c.object
<CustomObject>
    <fields>
        <fullName>SubType_Key__c</fullName>
        <label>SubType Key</label>
        <referenceTo>Contact_Us_SubType_Option__c</referenceTo>
        <relationshipLabel>ContactUs SubType2 Options</relationshipLabel>
        <relationshipName>Contact_Us_SubType2_Options</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>View__c</fullName>
        <label>View</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>ContactUs SubType2 Option</label>
    <nameField>
        <label>SubType2 Key</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ContactUs SubType2 Options</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Contact_Us_SubType_Option__c.object
<CustomObject>
    <fields>
        <fullName>Type_Key__c</fullName>
        <label>Type Key</label>
        <referenceTo>Contact_Us_Type_Option__c</referenceTo>
        <relationshipLabel>ContactUs SubType Options</relationshipLabel>
        <relationshipName>Contact_Us_SubType_Options</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>View__c</fullName>
        <label>View</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>ContactUs SubType Option</label>
    <nameField>
        <label>SubType Key</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ContactUs SubType Options</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Contact_Us_Type_Option__c.object
<CustomObject>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>AR</fullName>
                </value>
                <value>
                    <fullName>AT</fullName>
                </value>
                <value>
                    <fullName>BR</fullName>
                </value>
                <value>
                    <fullName>CA</fullName>
                </value>
                <value>
                    <fullName>CH</fullName>
                </value>
                <value>
                    <fullName>CL</fullName>
                </value>
                <value>
                    <fullName>CO</fullName>
                </value>
                <value>
                    <fullName>DE</fullName>
                </value>
                <value>
                    <fullName>ES</fullName>
                </value>
                <value>
                    <fullName>IT</fullName>
                </value>
                <value>
                    <fullName>JP</fullName>
                </value>
                <value>
                    <fullName>US</fullName>
                </value>
                <value>
                    <fullName>ZA</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Language__c</fullName>
        <label>Language</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>en</fullName>
                </value>
                <value>
                    <fullName>de</fullName>
                </value>
                <value>
                    <fullName>ja</fullName>
                </value>
                <value>
                    <fullName>fr</fullName>
                </value>
                <value>
                    <fullName>es</fullName>
                </value>
                <value>
                    <fullName>it</fullName>
                </value>
                <value>
                    <fullName>pt</fullName>
                </value>
                <value>
                    <fullName>en_ZA</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>View__c</fullName>
        <label>View</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>ContactUs Type Option</label>
    <nameField>
        <label>Type Key</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ContactUs Type Options</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ContactUsOptionService.cls
public with sharing class ContactUsOptionService {

    /**
     * It might be useful to change caseActions component (editCaseCmp.js), to stop using this method
     * and start using this List<Map<String, String>> getContactUsOptions(String language, String country, String masterOptionId, ContactUsOptionService.ContactUsOption contactUsOption)
     * which base on the parent Ids not the names of ContactUs records.
     */
    public List<Map<String, String>> getContactUsOptions(String masterOption, ContactUsOptionService.ContactUsOption contactUsOption) {
        Map<String, Map<String, String>> result = new Map<String, Map<String, String>>();
        List<SObject> contactUsOptions = new List<SObject>();
        String userLanguage = UserInfo.getLanguage().substringBefore('_');
        switch on contactUsOption {
            when TYPE {
                contactUsOptions = ContactUsTypeOptionSelector.newInstance().selectByLanguage(userLanguage);
            }
            when SUBTYPE {
                contactUsOptions = ContactUsSubTypeOptionSelector.newInstance().selectByLanguageAndMasterOption(userLanguage, masterOption);
            }
            when SUBTYPE2 {
                contactUsOptions = ContactUsSubType2OptionSelector.newInstance().selectByLanguageAndMasterOption(userLanguage, masterOption);
            }
        }
        for (SObject option : contactUsOptions) {
            result.put((String)option.get('Name'), LightningResult.prepareComboboxOption((String)option.get('Name'), (String)option.get('View__c')));
        }
        return result.values();
    }

    public ContactUsOptionService.TypeOptionWrapper getContactUsOptions(Id caseId) {
        List<Case> caseRecords =
            CaseSelector.newInstance().selectById(new Set<Id> { caseId });
        if (caseRecords.isEmpty()) {
            throw new Application.ApplicationException(Label.No_Records_Found);
        }

        ContactUsOptionService.TypeOptionWrapper tow = new ContactUsOptionService.TypeOptionWrapper(caseRecords.get(0));
        tow.optionsByField.put(ContactUsOptionService.ContactUsOption.TYPE.name().toLowerCase(), getContactUsOptions(null, ContactUsOptionService.ContactUsOption.TYPE));
        if (String.isNotBlank(tow.type)) {
            tow.optionsByField.put(ContactUsOptionService.ContactUsOption.SUBTYPE.name().toLowerCase(), getContactUsOptions(tow.type, ContactUsOptionService.ContactUsOption.SUBTYPE));
        }
        if (String.isNotBlank(tow.subType)) {
            tow.optionsByField.put(ContactUsOptionService.ContactUsOption.SUBTYPE2.name().toLowerCase(), getContactUsOptions(tow.subType, ContactUsOptionService.ContactUsOption.SUBTYPE2));
        }
        return tow;
    }

    public List<List<SObject>> getContactUsOptionsForBot(List<BotGetContactUsOptionsHandler.BotInput> inputs) {
        List<String> languages = new List<String>();
        List<String> masterTypeOptionLanguages = new List<String>();
        List<String> masterSubTypeOptionLanguages = new List<String>();
        Set<String> countries = new Set<String>();
        List<String> masterTypeOptionNames = new List<String>();
        List<String> masterSubTypeOptionNames = new List<String>();
        for (BotGetContactUsOptionsHandler.BotInput input : inputs) {
            if (String.isNotBlank(input.language)) {
                languages.add(input.language);
            }
            if (String.isNotBlank(input.country)) {
                countries.add(input.country);
            }
            if (String.isNotBlank(input.masterTypeOptionName)) {
                masterTypeOptionNames.add(input.masterTypeOptionName);
                masterTypeOptionLanguages.add(input.language);
            }
            if (String.isNotBlank(input.masterSubTypeOptionName)) {
                masterSubTypeOptionNames.add(input.masterSubTypeOptionName);
                masterSubTypeOptionLanguages.add(input.language);
            }
        }
        List<Contact_Us_Type_Option__c> contactUsTypeRecords = new List<Contact_Us_Type_Option__c>();
        if (!languages.isEmpty() || !countries.isEmpty()) {
            contactUsTypeRecords.addAll(ContactUsTypeOptionSelector.newInstance().selectByLanguageAndCountry(new Set<String> (languages), countries));
        }
        List<Contact_Us_SubType_Option__c> contactUsSubTypeRecords = new List<Contact_Us_SubType_Option__c>();
        List<Contact_Us_SubType2_Option__c> contactUsSub2TypeRecords = new List<Contact_Us_SubType2_Option__c>();
        if (!masterTypeOptionNames.isEmpty()) {
            contactUsSubTypeRecords.addAll(ContactUsSubTypeOptionSelector.newInstance().selectByMasterOptionNameAndLanguage(masterTypeOptionLanguages, masterTypeOptionNames));
        }
        if (!masterSubTypeOptionNames.isEmpty()) {
            contactUsSub2TypeRecords.addAll(ContactUsSubType2OptionSelector.newInstance().selectByMasterOptionNameAndLanguage(masterSubTypeOptionLanguages, masterSubTypeOptionNames));
        }

        List<List<SObject>> result = new List<List<SObject>>();
        for (BotGetContactUsOptionsHandler.BotInput input : inputs) {
            List<SObject> inputResults = new List<SObject>();
            if (!contactUsTypeRecords.isEmpty()) {
                for (Integer i = 0;i < contactUsTypeRecords.size(); i++) {
                    if (contactUsTypeRecords.get(i).Language__c == input.language &&
                        contactUsTypeRecords.get(i).Country__c.containsIgnoreCase(input.country)) {
                        inputResults.add(contactUsTypeRecords.get(i));
                        contactUsTypeRecords.remove(0);
                        i--;
                    }
                }
            }
            if (inputResults.isEmpty() && !contactUsSubTypeRecords.isEmpty()) {
                for (Integer i = 0;i < contactUsSubTypeRecords.size(); i++) {
                    if (contactUsSubTypeRecords.get(0).Type_Key__r.Language__c == input.language &&
                        contactUsSubTypeRecords.get(0).Type_Key__r.Name == input.masterTypeOptionName) {
                        inputResults.add(contactUsSubTypeRecords.get(0));
                        contactUsSubTypeRecords.remove(0);
                        i--;
                    }
                }
            }
            if (inputResults.isEmpty() && !contactUsSub2TypeRecords.isEmpty()) {
                for (Integer i = 0;i < contactUsSub2TypeRecords.size(); i++) {
                    if (contactUsSub2TypeRecords.get(0).SubType_Key__r.Type_Key__r.Language__c == input.language &&
                        contactUsSub2TypeRecords.get(0).SubType_Key__r.Name == input.masterSubTypeOptionName) {
                        inputResults.add(contactUsSub2TypeRecords.get(0));
                        contactUsSub2TypeRecords.remove(0);
                        i--;
                    }
                }
            }
            result.add(inputResults);
        }
        return result;
    }

    public static ContactUsOptionService newInstance() {
        return (ContactUsOptionService) Application.Service.newInstance(ContactUsOptionService.class);
    }

    public enum ContactUsOption {TYPE, SUBTYPE, SUBTYPE2}

    public static ContactUsOption toContactUsOption(String s) {
        for (ContactUsOption contactUsOption : ContactUsOption.values()) {
            if (contactUsOption.name().equalsIgnoreCase(s)) {
                return contactUsOption;
            }
        }
        return null;
    }

    public class TypeOptionWrapper {
        @AuraEnabled
        public String fieldName { get; set; }
        @AuraEnabled
        public String masterOptionValue { get; set; }
        @AuraEnabled
        public String caseId { get; set; }
        @AuraEnabled
        public String type { get; set; }
        @AuraEnabled
        public String subType { get; set; }
        @AuraEnabled
        public String subType2 { get; set; }
        @AuraEnabled
        public Map<String, List<Map<String, String>>> optionsByField {
            get {
                if (optionsByField == null) {
                    optionsByField = new Map<String, List<Map<String, String>>>();
                }
                return optionsByField;
            }
            set;
        }

        @TestVisible
        public ContactUsOption contactUsOption {
            get {
                if (this.contactUsOption == null) {
                    if (String.isNotBlank(fieldName)) {
                        this.contactUsOption = toContactUsOption(fieldName);
                    }
                }
                return this.contactUsOption;
            }
            private set;
        }

        public TypeOptionWrapper(Case c) {
            this.type = c.Type;
            this.subType = c.Sub_Type__c;
            this.subType2 = c.Sub_Type2__c;
        }

        public TypeOptionWrapper() {}
    }
}