src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Notification_Country_Code__c</fullName>
        <description>this field contains an ISO 3166-1 alpha-2 code, which is a two-letter country code defined in ISO 3166-1, part of the ISO 3166 standard</description>
        <label>Notification Country Code</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Country_Codes</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Queue_Key__c</fullName>
        <defaultValue>0</defaultValue>
        <description>0-New Case, 1 - OnHold, 2- Tech, 3 - Billing</description>
        <label>Queue Key</label>
        <precision>1</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

src/objects/Case_Queue_Assignment__mdt.object
<CustomObject>
    <description>Assigns queue by given country code.</description>
    <fields>
        <fullName>Billing_Cases__c</fullName>
        <label>Billing Cases</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>New_Cases__c</fullName>
        <label>New Cases</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>On_Hold_Cases__c</fullName>
        <label>On-Hold Cases</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Tech_Cases__c</fullName>
        <label>Tech Cases</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Case Queue Assignment</label>
    <pluralLabel>Case Queue Assignments</pluralLabel>
</CustomObject>

src/classes/CaseService.cls
public with sharing class CaseService {

    public static final String RECORD_TYPE_NAME_EXCO_COMPLAINT = 'Exco Complaint';
    public enum CaseActionType {BILLING_ESCALATION, TECH_ESCALATION, ON_HOLD_ESCALATION, BACK_TO_QUEUE, SPLIT_CASE, CLOSE}

    public static CaseService newInstance() {
        return (CaseService) Application.Service.newInstance(CaseService.class);
    }

    public void performCaseActions(CaseService.CaseActionWrapper caw) {
        fflib_ISObjectUnitOfWork uow = Application.UnitOfWork.newInstance();

        List<Case> caseRecords =
            CaseSelector.newInstance().selectByIdWithFieldsForCloningRecord(new Set<Id> { caw.caseId });

        if (caseRecords.size() != 1) {
            throw new Application.ApplicationException(Label.No_Records_Found);
        }

        caw.setCaseQueueAssignmentByCountryCode(CaseQueueAssignmentSelector.newInstance().selectAll());
        CaseDomain cases = CaseDomain.newInstance(caseRecords);
        Case currentCase = caseRecords.get(0);
        cases.setCaseActionFields(caw.caseAction, caw.caseActionReason);

        if (caw.isActionWithResponse() || caw.caseActionType == CaseService.CaseActionType.BACK_TO_QUEUE) {
            cases
                .setStatusField('Open')
                .setQueueKeyField(caw.queueKey)
                .setOwnerIdForCaseAction(caw);
            if (caw.isActionWithResponse()) {
                cases.setLastCaseCommentField(caw.response);
                if (String.isNotBlank(caw.response)) {
                    cases.createCaseComment(uow, caw.response.replaceAll('</p>', '\n').replaceAll('<[^>]+>',' '));
                    cases.sendEmailWithCaseActionsResponse(uow, currentCase, caw.response);
                }
            }
        } else {
            cases
                .setStatusField('Closed')
                .setOwnerToCurrentUser();
            if (caw.caseActionType == CaseService.CaseActionType.SPLIT_CASE) {
                cases.cloneCase(uow, new Map<String, Object> {
                    'Status' => 'Open',
                    'Queue_Key__c' => caw.queueKey,
                    'OwnerId' => cases.getOwnerIdForCaseAction(currentCase, caw)
                });
            }
        }
        uow.registerDirty(currentCase);
        uow.commitWork();
    }

    public Id getQueueId(Case c) {
        Id groupId;
        Case_Queue_Assignment__mdt caseQueueAssignment =
                CaseQueueAssignmentSelector.newInstance().selectAll().get(c.Notification_Country_Code__c);
        String queueName = c.RecordTypeId == Utils.getRecordTypeId(Case.SObjectType, CaseService.RECORD_TYPE_NAME_EXCO_COMPLAINT) ?
                CaseService.RECORD_TYPE_NAME_EXCO_COMPLAINT : caseQueueAssignment?.New_Cases__c.trim();
        if (queueName != null) {
            groupId = GroupSelector.newInstance().selectByTypeAndName('Queue', queueName)[0].Id;
        }
        return groupId;
    }

    public class CaseActionWrapper {
        public final List<CaseService.CaseActionType> ACTIONS_WITH_RESPONSE = new List<CaseService.CaseActionType> {
            CaseService.CaseActionType.BILLING_ESCALATION,
            CaseService.CaseActionType.ON_HOLD_ESCALATION,
            CaseService.CaseActionType.TECH_ESCALATION
        };

        public final Map<CaseService.CaseActionType, String> CASE_ACTION_TO_CASE_QUEUE_ASSIGNMENT_FIELD = new Map<CaseService.CaseActionType, String> {
            CaseService.CaseActionType.BILLING_ESCALATION => 'Billing_Cases__c',
            CaseService.CaseActionType.TECH_ESCALATION => 'Tech_Cases__c',
            CaseService.CaseActionType.ON_HOLD_ESCALATION => 'On_Hold_Cases__c',
            CaseService.CaseActionType.BACK_TO_QUEUE => 'New_Cases__c',
            CaseService.CaseActionType.SPLIT_CASE => 'New_Cases__c'
        };

        public final Map<CaseService.CaseActionType, Integer> CASE_ACTION_TO_QUEUE_KEY = new Map<CaseService.CaseActionType, Integer> {
            CaseService.CaseActionType.BILLING_ESCALATION => 3,
            CaseService.CaseActionType.TECH_ESCALATION => 2,
            CaseService.CaseActionType.ON_HOLD_ESCALATION => 1,
            CaseService.CaseActionType.BACK_TO_QUEUE => 0,
            CaseService.CaseActionType.SPLIT_CASE => 0
        };

        @AuraEnabled
        public String caseId { get; set; }
        @AuraEnabled
        public String caseAction { get; set; }
        @AuraEnabled
        public String caseActionReason { get; set; }
        @AuraEnabled
        public String response { get; set; }

        @TestVisible
        public CaseActionType caseActionType {
            get {
                if (this.caseActionType == null) {
                    if (String.isNotBlank(caseAction)) {
                        this.caseActionType = toCaseActionType(caseAction);
                    }
                }
                return this.caseActionType;
            }
            private set;
        }

        public Integer queueKey {
            get {
                if (this.queueKey == null) {
                    this.queueKey = CASE_ACTION_TO_QUEUE_KEY.get(caseActionType);
                }
                return this.queueKey;
            }
            private set;
        }

        public String caseQueueAssignmentField {
            get {
                if (this.caseQueueAssignmentField == null) {
                    this.caseQueueAssignmentField = CASE_ACTION_TO_CASE_QUEUE_ASSIGNMENT_FIELD.get(caseActionType);
                }
                return this.caseQueueAssignmentField;
            }
            private set;
        }

        public Map<String, Id> queueByQueueId {
            get {
                if (this.queueByQueueId == null) {
                    queueByQueueId = new Map<String, Id>();
                    for (Group queue : GroupSelector.newInstance().selectByType('Queue')) {
                        queueByQueueId.put(queue.Name, queue.Id);
                    }
                }
                return this.queueByQueueId;
            }
            private set;
        }

        public Map<String, Case_Queue_Assignment__mdt> caseQueueAssignmentByCountryCode;

        public Boolean isActionWithResponse() {
            return ACTIONS_WITH_RESPONSE.contains(caseActionType);
        }

        public void setCaseQueueAssignmentByCountryCode(Map<String, Case_Queue_Assignment__mdt> caseQueueAssignmentByCountryCode) {
            this.caseQueueAssignmentByCountryCode = caseQueueAssignmentByCountryCode;
        }
    }

    public static CaseActionType toCaseActionType(String s) {
        for (CaseActionType caseActionType : CaseActionType.values()) {
            if (caseActionType.name().equalsIgnoreCase(s.replaceAll('[^a-zA-Z]', '_'))) {
                return caseActionType;
            }
        }
        return null;
    }
}