src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Case_Action_Reason__c</fullName>
        <description>List of Case Action Reasons. Dependent on Case Actions list.</description>
        <label>Case Action Reason</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Case_Actions__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Closed - Case Resolved</fullName>
                </value>
                <value>
                    <fullName>Closed - New Question</fullName>
                </value>
                <value>
                    <fullName>Closed - Spam</fullName>
                </value>
                <value>
                    <fullName>Closed - Irate Customer</fullName>
                </value>
                <value>
                    <fullName>BTQ - Shift End</fullName>
                </value>
                <value>
                    <fullName>BTQ - Assign to Another Agent</fullName>
                </value>
                <value>
                    <fullName>BTQ - Accidentally Closed</fullName>
                </value>
                <value>
                    <fullName>Billing - Manual Refund Request</fullName>
                </value>
                <value>
                    <fullName>Billing - Billing Batch</fullName>
                </value>
                <value>
                    <fullName>Billing - Manual Cancellation</fullName>
                </value>
                <value>
                    <fullName>Billing - Invoice Request</fullName>
                </value>
                <value>
                    <fullName>Billing - Manual Pause Resume</fullName>
                </value>
                <value>
                    <fullName>Tech - Escalation to THD</fullName>
                </value>
                <value>
                    <fullName>On-Hold - Viewing History</fullName>
                </value>
                <value>
                    <fullName>On-Hold - Manual Free Month Addition</fullName>
                </value>
                <value>
                    <fullName>Split Case - New Question</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Case_Actions__c</fullName>
        <description>List of Case Actions. Dependent on case status.</description>
        <label>Case Actions</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Status</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Back to Queue</fullName>
                </value>
                <value>
                    <fullName>Billing Escalation</fullName>
                </value>
                <value>
                    <fullName>Close</fullName>
                </value>
                <value>
                    <fullName>Split Case</fullName>
                </value>
                <value>
                    <fullName>Tech Escalation</fullName>
                </value>
                <value>
                    <fullName>On-Hold Escalation</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Mass_Response__c</fullName>
        <label>Mass Response</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>GAMBA KOFU game error</fullName>
                    <label>GAMBA, EHIME</label>
                </value>
                <value>
                    <fullName>J2 CATCH UP</fullName>
                </value>
                <value>
                    <fullName>Buffering, quality issue</fullName>
                </value>
                <value>
                    <fullName>Issue Compensation</fullName>
                </value>
                <value>
                    <fullName>CA Quality</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Notification_Country_Code__c</fullName>
        <description>this field contains an ISO 3166-1 alpha-2 code, which is a two-letter country code defined in ISO 3166-1, part of the ISO 3166 standard</description>
        <label>Notification Country Code</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Country_Codes</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Notification_Language_Code__c</fullName>
        <description>This field contains a language tag, adhering the best practices as described in rfc5646</description>
        <label>Notification Language Code</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Language_Tags</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Sub_Type2__c</fullName>
        <label>Sub-Type2</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Sub_Type__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>How do I amend my order?</fullName>
                </value>
                <value>
                    <fullName>How do I access the &quot;My Account&quot; area?</fullName>
                </value>
                <value>
                    <fullName>Help with Error codes</fullName>
                </value>
                <value>
                    <fullName>How do I cancel my subscription?</fullName>
                </value>
                <value>
                    <fullName>How do I change my marketing preferences?</fullName>
                </value>
                <value>
                    <fullName>How do I change my password?</fullName>
                </value>
                <value>
                    <fullName>How do I change my payment method?</fullName>
                </value>
                <value>
                    <fullName>How do I change my personal details?</fullName>
                </value>
                <value>
                    <fullName>How do I change or update my payment method?</fullName>
                </value>
                <value>
                    <fullName>How do I install my DAZN TV device?</fullName>
                </value>
                <value>
                    <fullName>How do I order a new DAZN TV device</fullName>
                </value>
                <value>
                    <fullName>How do I sign in to DAZN for Business?</fullName>
                </value>
                <value>
                    <fullName>How do I sign up to DAZN for Business?</fullName>
                </value>
                <value>
                    <fullName>How do I track my order?</fullName>
                </value>
                <value>
                    <fullName>How do I use the DAZN TV device?</fullName>
                </value>
                <value>
                    <fullName>How do I view my bill?</fullName>
                </value>
                <value>
                    <fullName>I can&apos;t find the content I want to view</fullName>
                </value>
                <value>
                    <fullName>I can&apos;t pair my remote</fullName>
                </value>
                <value>
                    <fullName>I cannot sign in to DAZN for Business</fullName>
                </value>
                <value>
                    <fullName>I cannot sign in to the &quot;My Account&quot; area</fullName>
                </value>
                <value>
                    <fullName>I did not receive a password reset email</fullName>
                </value>
                <value>
                    <fullName>I forgot my email</fullName>
                </value>
                <value>
                    <fullName>I forgot my password</fullName>
                </value>
                <value>
                    <fullName>I have a blank screen</fullName>
                </value>
                <value>
                    <fullName>I have no audio</fullName>
                </value>
                <value>
                    <fullName>I have problems with my delivery</fullName>
                </value>
                <value>
                    <fullName>I was incorrectly charged</fullName>
                </value>
                <value>
                    <fullName>I&apos;m unable to sign up</fullName>
                </value>
                <value>
                    <fullName>I&apos;ve lost my remote</fullName>
                </value>
                <value>
                    <fullName>My DAZN App Doesn&apos;t Open</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Sub_Type__c</fullName>
        <description>Case sub-types, this field is dependent on case type field.</description>
        <label>Sub-Type</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Type</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>About DAZN for Business</fullName>
                </value>
                <value>
                    <fullName>STB Delivery &amp; installation</fullName>
                </value>
                <value>
                    <fullName>Creating a new account</fullName>
                </value>
                <value>
                    <fullName>Username and Password</fullName>
                </value>
                <value>
                    <fullName>Update my details</fullName>
                </value>
                <value>
                    <fullName>Remote Control Issues</fullName>
                </value>
                <value>
                    <fullName>Billing</fullName>
                </value>
                <value>
                    <fullName>Problems Watching</fullName>
                </value>
                <value>
                    <fullName>DAZN TV device issues</fullName>
                </value>
                <value>
                    <fullName>My Account</fullName>
                </value>
                <value>
                    <fullName>Abandoned Chat</fullName>
                </value>
                <value>
                    <fullName>Unable to classify</fullName>
                </value>
                <value>
                    <fullName>Missed Chat</fullName>
                </value>
                <value>
                    <fullName>About DAZN</fullName>
                    <isActive>false</isActive>
                    <label>About DAZN</label>
                </value>
                <value>
                    <fullName>Access to My Account</fullName>
                    <isActive>false</isActive>
                    <label>Access to My Account</label>
                </value>
                <value>
                    <fullName>Account Reactivation through SNL</fullName>
                    <isActive>false</isActive>
                    <label>Account Reactivation through SNL</label>
                </value>
                <value>
                    <fullName>Age Verification</fullName>
                    <isActive>false</isActive>
                    <label>Age Verification</label>
                </value>
                <value>
                    <fullName>App Feedback</fullName>
                    <isActive>false</isActive>
                    <label>App Feedback</label>
                </value>
                <value>
                    <fullName>App Installation &amp; Use</fullName>
                    <isActive>false</isActive>
                    <label>App Installation &amp; Use</label>
                </value>
                <value>
                    <fullName>App Issues</fullName>
                    <isActive>false</isActive>
                    <label>App Issues</label>
                </value>
                <value>
                    <fullName>App features</fullName>
                    <isActive>false</isActive>
                    <label>App features</label>
                </value>
                <value>
                    <fullName>BILDplus</fullName>
                    <isActive>false</isActive>
                    <label>BILDplus</label>
                </value>
                <value>
                    <fullName>Cancellation</fullName>
                    <isActive>false</isActive>
                    <label>Cancellation</label>
                </value>
                <value>
                    <fullName>Cancellation reasons</fullName>
                    <isActive>false</isActive>
                    <label>Cancellation reasons</label>
                </value>
                <value>
                    <fullName>Cancelling my account</fullName>
                    <isActive>false</isActive>
                    <label>Cancelling my account</label>
                </value>
                <value>
                    <fullName>Casting to another device</fullName>
                    <isActive>false</isActive>
                    <label>Casting to another device</label>
                </value>
                <value>
                    <fullName>Changing my subscription type</fullName>
                    <isActive>false</isActive>
                    <label>Changing my subscription type</label>
                </value>
                <value>
                    <fullName>Comment about marketing or adverts</fullName>
                    <isActive>false</isActive>
                    <label>Comment about marketing or adverts</label>
                </value>
                <value>
                    <fullName>Content Feedback</fullName>
                    <isActive>false</isActive>
                    <label>Content Feedback</label>
                </value>
                <value>
                    <fullName>Customer Service</fullName>
                    <isActive>false</isActive>
                    <label>Customer Service</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Thread_Id__c</fullName>
        <formula>&quot;ref:_&quot; &amp; LEFT($Organization.Id,5) &amp; SUBSTITUTE(RIGHT($Organization.Id,11), &quot;0&quot;, &quot;&quot; )&amp; &quot;._&quot; &amp; LEFT(Id,5) &amp; SUBSTITUTE(Left(RIGHT(Id,10), 5), &quot;0&quot;, &quot;&quot;) &amp; RIGHT(Id,5) &amp; &quot;:ref&quot;</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Thread Id</label>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

src/classes/CaseSelector.cls
public inherited sharing class CaseSelector extends fflib_SObjectSelector {
    public static CaseSelector newInstance() {
        return (CaseSelector) Application.Selector.newInstance(Case.SObjectType);
    }

    public List<Schema.SObjectField> getSObjectFieldList() {
        return new List<Schema.SObjectField> {
            Case.Status,
            Case.Type,
            Case.Sub_Type__c,
            Case.Sub_Type2__c,
            Case.Notification_Country_Code__c,
            Case.Notification_Language_Code__c,
            Case.Status,
            Case.Notification_Country_Code__c,
            Case.Notification_Language_Code__c,
            Case.AccountId,
            Case.CaseNumber,
            Case.RecordTypeId
        };
    }

    public Schema.SObjectType getSObjectType() {
        return Case.SObjectType;
    }

    public List<Case> selectById(Set<Id> idSet) {
        return (List<Case>) selectSObjectsById(idSet);
    }

    public List<Case> selectByIdWithFieldsForCloningRecord(Set<Id> idSet) {
        Set<String> fields = new Set<String> {
            'Id',
            'RecordType.Name',
            'ContactId',
            'Contact.Email',
            'Status',
            'Origin',
            'Case_Actions__c',
            'Case_Action_Reason__c',
            'Reason',
            'Notification_Country_Code__c',
            'Notification_Language_Code__c',
            'Type',
            'Sub_Type__c',
            'Sub_Type2__c',
            'Subject',
            'AccountId',
            'Mass_Response__c',
            'Priority',
            'SuppliedEmail',
            'Thread_Id__c'
        };
        return Database.query(
            newQueryFactory()
                .selectFields(fields)
                .setCondition('Id IN :idSet')
                .toSOQL()
        );
    }
    public List<Case> selectByFromAddressSubjectAndCreatedAfter(String fromAddress, String subject, Datetime createdAfter) {
        return Database.query(
                newQueryFactory()
                        .setCondition('SuppliedEmail = :fromAddress AND Subject = :subject AND CreatedDate > :createdAfter')
                        .toSOQL()
        );
    }
}