src/objects/Contact_Us_SubType2_Option__c.object
<CustomObject>
    <fields>
        <fullName>Case_Resolution_Owner__c</fullName>
        <description>If &apos;External&apos;, show Contact_Us_SubType2_Option__c.Case_Resolution_Text
If custom provider(s) separated by ; , show Custom_Provider__c.Contact_Custom_Provider_Text</description>
        <inlineHelpText>If &apos;External&apos;, show Contact_Us_SubType2_Option__c.Case_Resolution_Text
If custom provider(s) separated by ; , show Custom_Provider__c.Contact_Custom_Provider_Text</inlineHelpText>
        <label>Case Resolution Owner</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SubType_Key__c</fullName>
        <label>SubType Key</label>
        <referenceTo>Contact_Us_SubType_Option__c</referenceTo>
        <relationshipLabel>ContactUs SubType2 Options</relationshipLabel>
        <relationshipName>Contact_Us_SubType2_Options</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>View__c</fullName>
        <label>View</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>ContactUs SubType2 Option</label>
    <nameField>
        <label>SubType2 Key</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ContactUs SubType2 Options</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Contact_Us_SubType_Option__c.object
<CustomObject>
    <fields>
        <fullName>Type_Key__c</fullName>
        <label>Type Key</label>
        <referenceTo>Contact_Us_Type_Option__c</referenceTo>
        <relationshipLabel>ContactUs SubType Options</relationshipLabel>
        <relationshipName>Contact_Us_SubType_Options</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>View__c</fullName>
        <label>View</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>ContactUs SubType Option</label>
    <nameField>
        <label>SubType Key</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ContactUs SubType Options</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Contact_Us_Type_Option__c.object
<CustomObject>
    <fields>
        <fullName>Case_Resolution_Owner__c</fullName>
        <label>Case Resolution Owner</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>DAZN</fullName>
                </value>
                <value>
                    <fullName>External</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Language__c</fullName>
        <label>Language</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>en</fullName>
                </value>
                <value>
                    <fullName>de</fullName>
                </value>
                <value>
                    <fullName>ja</fullName>
                </value>
                <value>
                    <fullName>fr</fullName>
                </value>
                <value>
                    <fullName>es</fullName>
                </value>
                <value>
                    <fullName>it</fullName>
                </value>
                <value>
                    <fullName>pt</fullName>
                </value>
                <value>
                    <fullName>en_ZA</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Provider_Type__c</fullName>
        <label>Provider Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>DAZN</fullName>
                </value>
                <value>
                    <fullName>Docomo</fullName>
                </value>
                <value>
                    <fullName>Non-member</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>View__c</fullName>
        <label>View</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>ContactUs Type Option</label>
    <nameField>
        <label>Type Key</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ContactUs Type Options</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ContactUsSubType2OptionSelectorTest.cls
@IsTest
private class ContactUsSubType2OptionSelectorTest {
    @IsTest
    private static void testSelectByLanguageAndMasterOption() {
        String name = 'Test';
        String subType2Name = 'Test Subtype2';
        String language = 'en';
        Contact_Us_Type_Option__c contactUsTypeOption = new Contact_Us_Type_Option__c(
            Name = name,
            View__c = name,
            Language__c = language,
            Case_Resolution_Owner__c = 'DAZN',
            Provider_Type__c = 'DAZN'
        );
        insert contactUsTypeOption;
        Contact_Us_SubType_Option__c contactUsSubTypeOption = new Contact_Us_SubType_Option__c(
            Name = name,
            View__c = name,
            Type_Key__c = contactUsTypeOption.Id
        );
        insert contactUsSubTypeOption;
        Contact_Us_SubType2_Option__c contactUsSubType2Option = new Contact_Us_SubType2_Option__c(
            Name = subType2Name,
            View__c = subType2Name,
            SubType_Key__c = contactUsSubTypeOption.Id
        );
        insert contactUsSubType2Option;

        // Query
        List<Contact_Us_SubType2_Option__c> contactUsSubType2Options =
            ContactUsSubType2OptionSelector.newInstance().selectByLanguageAndMasterOption(language, name);

        // Assert
        System.assertEquals(contactUsSubType2Option.Id, contactUsSubType2Options.get(0).Id);
    }

    @IsTest
    private static void testSelectByMasterOptionNameAndLanguage() {
        String name = 'Test';
        String subType2Name = 'Test Subtype2';
        String language = 'en';
        Contact_Us_Type_Option__c contactUsTypeOption = new Contact_Us_Type_Option__c(
            Name = name,
            View__c = name,
            Language__c = language,
            Case_Resolution_Owner__c = 'DAZN',
            Provider_Type__c = 'DAZN'
        );
        insert contactUsTypeOption;
        Contact_Us_SubType_Option__c contactUsSubTypeOption = new Contact_Us_SubType_Option__c(
            Name = name,
            View__c = name,
            Type_Key__c = contactUsTypeOption.Id
        );
        insert contactUsSubTypeOption;
        Contact_Us_SubType2_Option__c contactUsSubType2Option = new Contact_Us_SubType2_Option__c(
            Name = subType2Name,
            View__c = subType2Name,
            SubType_Key__c = contactUsSubTypeOption.Id
        );
        insert contactUsSubType2Option;

        // Query
        List<Contact_Us_SubType2_Option__c> contactUsSubType2Options =
            ContactUsSubType2OptionSelector.newInstance().selectByMasterOptionNameAndLanguage(new List<String>{language}, new List<String>{contactUsSubTypeOption.Name});

        // Assert
        System.assertEquals(contactUsSubType2Option.Id, contactUsSubType2Options.get(0).Id);
    }
}