src/objects/CustomerAccount__c.object
<CustomObject>
    <description>DAZN Billing Account object.  An account is a customer account that collects all of the critical information about the customer, such as contact information, payment terms, and payment methods. You can use a customer account to track subscriptions, amendments, and transactions, such as invoices and payments.</description>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Billing Accounts</relationshipLabel>
        <relationshipName>BillingAccount</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>External_Id__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>External Id</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>DAZN Billing Account</label>
    <nameField>
        <label>Billing Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DAZN Billing Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/PaymentMethod__c.object
<CustomObject>
    <description>PaymentMethod contains information on how the contact pays for the account. In order to activate an account, you need to create a payment method.</description>
    <fields>
        <fullName>BillingAccount__c</fullName>
        <label>Billing Account</label>
        <referenceTo>CustomerAccount__c</referenceTo>
        <relationshipLabel>Payment Methods</relationshipLabel>
        <relationshipName>Payment_Methods</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>External_Id__c</fullName>
        <externalId>true</externalId>
        <label>External Id</label>
        <length>32</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>ACH</fullName>
                </value>
                <value>
                    <fullName>BankTransfer</fullName>
                </value>
                <value>
                    <fullName>Cash</fullName>
                </value>
                <value>
                    <fullName>Check</fullName>
                </value>
                <value>
                    <fullName>CreditCard</fullName>
                </value>
                <value>
                    <fullName>CreditCardReferenceTransaction</fullName>
                </value>
                <value>
                    <fullName>DebitCard</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>PayPal</fullName>
                </value>
                <value>
                    <fullName>WireTransfer</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>DAZN Payment Method</label>
    <nameField>
        <label>Payment Method Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DAZN Payment Methods</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/DAZNBillingAccountSelector.cls
public inherited sharing class DAZNBillingAccountSelector extends fflib_SObjectSelector {

    public static DAZNBillingAccountSelector newInstance() {
        return (DAZNBillingAccountSelector) Application.Selector.newInstance(CustomerAccount__c.SObjectType);
    }

    public List<Schema.SObjectField> getSObjectFieldList() {
        return new List<Schema.SObjectField> {
                CustomerAccount__c.Id,
                CustomerAccount__c.External_Id__c
        };
    }

    public Schema.SObjectType getSObjectType() {
        return CustomerAccount__c.SObjectType;
    }

    public List<CustomerAccount__c> selectBillingAccountByExternalId(Set<String> externalIds) {
        fflib_QueryFactory query = newQueryFactory();
        query.setCondition('External_Id__c IN :externalIds');

        return (List<CustomerAccount__c>) Database.query(query.toSOQL());
    }

    public List<CustomerAccount__c> selectBillingAccountByAccountId(Set<Id> accountIds) {
        fflib_QueryFactory query = newQueryFactory();
        query.setCondition('Account__c IN :accountIds');
        query.subselectQuery('Payment_Methods__r').selectFields(new Set<String>{'Type__c'});
        return (List<CustomerAccount__c>) Database.query(query.toSOQL());
    }
}