src/objects/Event__c.object
<CustomObject>
    <fields>
        <fullName>Record_Type__c</fullName>
        <label>Record Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Independent_Ecommerce</fullName>
                    <label>Independent (ecommerce)</label>
                </value>
                <value>
                    <fullName>Independent_Bank_Transfer</fullName>
                    <label>Independent (bank transfer)</label>
                </value>
                <value>
                    <fullName>Enterprise_Parent</fullName>
                    <label>Enterprise Parent</label>
                </value>
                <value>
                    <fullName>Enterprise_Child</fullName>
                    <label>Enterprise Child</label>
                </value>
                <value>
                    <fullName>Third_Party</fullName>
                </value>
                <value>
                    <fullName>IndependentEcommerce</fullName>
                    <isActive>false</isActive>
                    <label>IndependentEcommerce</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Related_Record_Id__c</fullName>
        <description>Id of the record this Event is related with</description>
        <label>Related Record Id</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Validated</fullName>
                </value>
                <value>
                    <fullName>Processed</fullName>
                </value>
                <value>
                    <fullName>Processed with Errors</fullName>
                </value>
                <value>
                    <fullName>Failed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>CaseCreated</fullName>
                </value>
                <value>
                    <fullName>CustomerCreated</fullName>
                </value>
                <value>
                    <fullName>CustomerUpdated</fullName>
                </value>
                <value>
                    <fullName>DeviceRegistered</fullName>
                </value>
                <value>
                    <fullName>DeviceUnregistered</fullName>
                </value>
                <value>
                    <fullName>LeadCreated</fullName>
                </value>
                <value>
                    <fullName>OrderCreated</fullName>
                </value>
                <value>
                    <fullName>OrderUpdated</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Event</label>
    <nameField>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/EventSelector.cls
public inherited sharing class EventSelector extends fflib_SObjectSelector {
    public static EventSelector newInstance() {
        return (EventSelector) Application.Selector.newInstance(Event__c.SObjectType);
    }

    public List<Schema.SObjectField> getSObjectFieldList() {
        return new List<Schema.SObjectField> {
                Event__c.Status__c,
                Event__c.Name,
                Event__c.Record_Type__c,
                Event__c.Type__c,
                Event__c.Related_Record_Id__c
        };
    }

    public Schema.SObjectType getSObjectType() {
        return Event__c.SObjectType;
    }

    public List<Event__c> selectById(Set<Id> idSet) {
        return (List<Event__c>) selectSObjectsById(idSet);
    }

    public List<Event__c> selectByRelatedRecordId(Set<Id> relatedRecordIdSet, String eventType) {
        return Database.query(
                newQueryFactory()
                        .setCondition('Related_Record_Id__c IN :relatedRecordIdSet AND Type__c = :eventType')
                        .toSOQL()
        );
    }

    public List<Event__c> selectByNameAndType(Set<String> nameSet, EventDomain.EventType eType) {
        return Database.query(
                newQueryFactory()
                        .setCondition('Name IN :nameSet AND Type__c = \'' + eType.name() + '\'')
                        .toSOQL()
        );
    }
}