src/objects/History_Tracking__c.object
<CustomObject>
    <fields>
        <fullName>Record_Id__c</fullName>
        <externalId>true</externalId>
        <label>Record Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>History Tracking</label>
    <nameField>
        <displayFormat>HS-{0000000}</displayFormat>
        <label>SObject History Tracking Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>History Tracking</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/HistoryTrackingSelectorTest.cls
/**
 * Unit test class for HistoryTrackingSelector class.
 *
 * @author      Nishant Khandelwal(nishant.khandelwal@dazn.com)
 * @created     Sept 2021
 */
@IsTest(isParallel=true)
private class HistoryTrackingSelectorTest {

    @IsTest
    static void testselectHistoryRecordsByRecordId() {

        Id recordId = fflib_IDGenerator.generate(History_Tracking__c.SObjectType);
        History_Tracking__c historyTracking = TestUtils.createHistoryTrackingRecord(recordId);
        insert historyTracking;
        List<History_Tracking__c> historyTrackingList = HistoryTrackingSelector.newInstance().selectHistoryRecordsByRecordId(new Set<Id> {recordId});

        System.assertEquals(1, historyTrackingList.size());
        System.assertEquals(recordId, historyTrackingList[0].Record_Id__c);
    }
}