src/objects/Order_Item__c.object
<CustomObject>
    <description>Used to capture the Order Items</description>
    <fields>
        <fullName>Quantity__c</fullName>
        <label>Quantity</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Serial_Number__c</fullName>
        <label>Serial Number</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Unique_Id__c</fullName>
        <externalId>true</externalId>
        <label>Unique Id</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Order Item</label>
    <nameField>
        <label>Order Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Order Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/OrderItemSelector.cls
public inherited sharing class OrderItemSelector extends fflib_SObjectSelector {
    public static OrderItemSelector newInstance() {
        return (OrderItemSelector) Application.Selector.newInstance(Order_Item__c.SObjectType);
    }

    public List<Schema.SObjectField> getSObjectFieldList() {
        return new List<Schema.SObjectField> {
                Order_Item__c.Unique_Id__c,
                Order_Item__c.Serial_Number__c,
                Order_Item__c.Quantity__c,
                Order_Item__c.Name
        };
    }

    public Schema.SObjectType getSObjectType() {
        return Order_Item__c.SObjectType;
    }

    public List<Order_Item__c> selectByUniqueId(Set<String> orderItemUniqueIds) {
        return Database.query(
                newQueryFactory()
                .setCondition('Unique_Id__c IN :orderItemUniqueIds')
                .toSOQL()
        );
    }
}