src/objects/Product__c.object
<CustomObject>
    <fields>
        <fullName>Price_List__c</fullName>
        <description>Base for the List price</description>
        <label>Price List</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Per Billing Period</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>DAZN Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DAZN Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ProductRatePlan__c.object
<CustomObject>
    <description>The Rate Plan associated with a Product.</description>
    <fields>
        <fullName>ExternalId__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>External Id</label>
        <length>32</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <label>Product</label>
        <referenceTo>Product__c</referenceTo>
        <relationshipName>Product_Rate_Plans</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>DAZN Product Rate Plan</label>
    <nameField>
        <label>Rate Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DAZN Product Rate Plans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/DAZNProductRatePlanSelector.cls
public inherited sharing class DAZNProductRatePlanSelector extends fflib_SObjectSelector {

    public static DAZNProductRatePlanSelector newInstance() {
        return (DAZNProductRatePlanSelector) Application.Selector.newInstance(ProductRatePlan__c.SObjectType);
    }

    public List<Schema.SObjectField> getSObjectFieldList() {
        return new List<Schema.SObjectField> {
                ProductRatePlan__c.Id,
                ProductRatePlan__c.ExternalId__c,
                ProductRatePlan__c.Product__c
        };
    }

    public Schema.SObjectType getSObjectType() {
        return ProductRatePlan__c.SObjectType;
    }

    public List<ProductRatePlan__c> selectById(Set<Id> productRatePlanIds) {
        Set<String> fields = new Set<String> {
                'Id',
                'Name',
                'ExternalId__c',
                'Product__c',
                'Product__r.Price_List__c'
        };
        return Database.query(
                newQueryFactory()
                        .selectFields(fields)
                        .setCondition('Id IN :productRatePlanIds')
                        .toSOQL()
        );
    }
    public List<ProductRatePlan__c> selectProductRatePlanByExternalId(Set<String> externalIds) {
        fflib_QueryFactory query = newQueryFactory();
        query.setCondition('ExternalId__c IN :externalIds');

        return (List<ProductRatePlan__c>) Database.query(query.toSOQL());
    }
}