src/objects/Product__c.object
<CustomObject>
    <fields>
        <fullName>EffectiveEndDate__c</fullName>
        <label>Effective End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Price_List__c</fullName>
        <description>Base for the List price</description>
        <label>Price List</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Per Billing Period</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>DAZN Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DAZN Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ProductRatePlan__c.object
<CustomObject>
    <description>The Rate Plan associated with a Product.</description>
    <fields>
        <fullName>EffectiveEndDate__c</fullName>
        <label>Effective End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <label>Product</label>
        <referenceTo>Product__c</referenceTo>
        <relationshipName>Product_Rate_Plans</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>DAZN Product Rate Plan</label>
    <nameField>
        <label>Rate Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DAZN Product Rate Plans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/ProductRatePlanCharge__c.object
<CustomObject>
    <fields>
        <fullName>Model__c</fullName>
        <label>Model</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Flat Fee</fullName>
                </value>
                <value>
                    <fullName>Volume</fullName>
                </value>
                <value>
                    <fullName>Tiered</fullName>
                </value>
                <value>
                    <fullName>Overage</fullName>
                </value>
                <value>
                    <fullName>Tiered with Overage</fullName>
                </value>
                <value>
                    <fullName>Discount-Fixed Amount</fullName>
                </value>
                <value>
                    <fullName>Discount-Percentage</fullName>
                </value>
                <value>
                    <fullName>Per Unit Pricing</fullName>
                </value>
                <value>
                    <fullName>Per Unit</fullName>
                    <isActive>false</isActive>
                    <label>Per Unit</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ProductRatePlan__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product Rate Plan</label>
        <referenceTo>ProductRatePlan__c</referenceTo>
        <relationshipName>Product_Rate_Plan_Charge</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>DAZN Product Rate Plan Charge</label>
    <nameField>
        <label>Product Rate Plan Charge Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DAZN Product Rate Plan Charge</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Subscription__c.object
<CustomObject>
    <description>A subscription is a product or service that has recurring charges, such as a monthly flat fee or charges based on usage. Subscriptions can also include one-time charges, such as activation fees.</description>
    <fields>
        <fullName>SubscriptionEndDate__c</fullName>
        <description>This is when the subscription ends. This is always equal to term end date, unless the subscription has been cancelled. If the subscription has been cancelled, this is set to the cancellation date.</description>
        <label>Subscription End Date</label>
        <type>Date</type>
    </fields>
    <label>DAZN Subscription</label>
    <nameField>
        <displayFormat>A-S{00000000}</displayFormat>
        <label>Subscription Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DAZN Subscriptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/SubscriptionProductCharge__c.object
<CustomObject>
    <fields>
        <fullName>EffectiveEndDate__c</fullName>
        <description>The date when the (segmented) charge ends (or ended).</description>
        <label>Effective End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ListPriceBase__c</fullName>
        <label>List Price Base</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Per Month</fullName>
                </value>
                <value>
                    <fullName>Per Billing Period</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Model__c</fullName>
        <label>Model</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ProductRatePlanCharge__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>DAZN Product Rate Plan Charge</label>
        <referenceTo>ProductRatePlanCharge__c</referenceTo>
        <relationshipLabel>DAZN Subscription Product &amp; Charges</relationshipLabel>
        <relationshipName>DAZN_Subscription_Product_Charges</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ProductRatePlan__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>DAZN Product Rate Plan</label>
        <referenceTo>ProductRatePlan__c</referenceTo>
        <relationshipLabel>DAZN Subscription Product &amp; Charges</relationshipLabel>
        <relationshipName>DAZN_Subscription_Product_Charges</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product (Deprecated)</label>
        <referenceTo>Product__c</referenceTo>
        <relationshipLabel>Subscription Product &amp; Charges</relationshipLabel>
        <relationshipName>Subscription_Product_And_Charges</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <label>Quantity</label>
        <precision>18</precision>
        <scale>3</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>RatePlanName__c</fullName>
        <label>Rate Plan Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Subscription__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Subscription</label>
        <referenceTo>Subscription__c</referenceTo>
        <relationshipLabel>Subscription Product &amp; Charges</relationshipLabel>
        <relationshipName>Subscription_Products_Charge</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>DAZN Subscription Product &amp; Charge</label>
    <nameField>
        <label>Subscription Charge Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DAZN Subscription Product &amp; Charges</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/DAZNSubscriptionProductChargeDomain.cls
public with sharing class DAZNSubscriptionProductChargeDomain extends ApplicationDomain {
    public static DAZNSubscriptionProductChargeDomain newInstance(List<SubscriptionProductCharge__c> subscriptionProductCharges) {
        return (DAZNSubscriptionProductChargeDomain) Application.Domain.newInstance(subscriptionProductCharges);
    }

    public DAZNSubscriptionProductChargeDomain(List<SubscriptionProductCharge__c> subscriptionProductCharges) {
        super(subscriptionProductCharges);
    }

    public override void onBeforeInsert() {
        populateFromProductRatePlanAndChargeData();
        populateQuantityField();
    }

    public override void onAfterInsert() {
        populateEffectiveEndDate();
    }

    public void populateFromProductRatePlanAndChargeData() {
        for(SubscriptionProductCharge__c subscriptionProductCharge : (List<SubscriptionProductCharge__c>)getRecordsWithNotBlankFieldValues(new Set<Schema.SObjectField> {Schema.SubscriptionProductCharge__c.ProductRatePlan__c, Schema.SubscriptionProductCharge__c.ProductRatePlanCharge__c})) {
            populateFromProductRatePlan(productRatePlansByIds, subscriptionProductCharge);
            populateFromProductRatePlanCharge(productRatePlanChargesByIds, subscriptionProductCharge);
        }
    }

    private void populateFromProductRatePlan(Map<Id, ProductRatePlan__c> productRatePlansByIds, SubscriptionProductCharge__c subscriptionProductCharge) {
        if (productRatePlansByIds.get(subscriptionProductCharge.ProductRatePlan__c) != null) {
            subscriptionProductCharge.RatePlanName__c = subscriptionProductCharge.RatePlanName__c == null ? productRatePlansByIds.get(subscriptionProductCharge.ProductRatePlan__c).Name : subscriptionProductCharge.RatePlanName__c;
            subscriptionProductCharge.Product__c = subscriptionProductCharge.Product__c == null ? productRatePlansByIds.get(subscriptionProductCharge.ProductRatePlan__c).Product__c : subscriptionProductCharge.Product__c;
            subscriptionProductCharge.ListPriceBase__c = subscriptionProductCharge.ListPriceBase__c == null ? productRatePlansByIds.get(subscriptionProductCharge.ProductRatePlan__c).Product__r.Price_List__c : subscriptionProductCharge.ListPriceBase__c;
        }
    }

    private void populateFromProductRatePlanCharge(Map<Id, ProductRatePlanCharge__c> productRatePlanChargesByIds, SubscriptionProductCharge__c subscriptionProductCharge) {
        if (productRatePlanChargesByIds.get(subscriptionProductCharge.ProductRatePlanCharge__c) != null) {
            subscriptionProductCharge.Name = subscriptionProductCharge.Name == null ? productRatePlanChargesByIds.get(subscriptionProductCharge.ProductRatePlanCharge__c).Name : subscriptionProductCharge.Name;
            subscriptionProductCharge.Model__c = subscriptionProductCharge.Model__c == null ? productRatePlanChargesByIds.get(subscriptionProductCharge.ProductRatePlanCharge__c).Model__c : subscriptionProductCharge.Model__c;
        }
    }

    private Map<Id, ProductRatePlanCharge__c> productRatePlanChargesByIds {
        get {
            if (productRatePlanChargesByIds == null) {
                productRatePlanChargesByIds = new Map<Id, ProductRatePlanCharge__c>(
                        DAZNProductRatePlanChargeSelector.newInstance().selectById(productRatePlanChargeIds));
            }
            return productRatePlanChargesByIds;
        }
        set;
    }

    private Map<Id, ProductRatePlan__c> productRatePlansByIds {
        get {
            if (productRatePlansByIds == null) {
                productRatePlansByIds = new Map<Id, ProductRatePlan__c>(
                        DAZNProductRatePlanSelector.newInstance().selectById(productRatePlanIds));
            }
            return productRatePlansByIds;
        }
        set;
    }

    private Set<Id> productRatePlanChargeIds {
        get {
            if (productRatePlanChargeIds == null) {
                productRatePlanChargeIds = new Set<Id>();
                for (SubscriptionProductCharge__c subscriptionProductCharge : (List<SubscriptionProductCharge__c>) getRecordsWithNotBlankFieldValues(Schema.SubscriptionProductCharge__c.ProductRatePlanCharge__c)) {
                    productRatePlanChargeIds.add(subscriptionProductCharge.ProductRatePlanCharge__c);
                }
            }
            return productRatePlanChargeIds;
        }
        set;
    }

    private Set<Id> productRatePlanIds {
        get {
            if (productRatePlanIds == null) {
                productRatePlanIds = new Set<Id>();
                for (SubscriptionProductCharge__c subscriptionProductCharge : (List<SubscriptionProductCharge__c>)getRecordsWithNotBlankFieldValues(Schema.SubscriptionProductCharge__c.ProductRatePlan__c)) {
                    productRatePlanIds.add(subscriptionProductCharge.ProductRatePlan__c);
                }
            }
            return productRatePlanIds;
        }
        set;
    }

    public void populateQuantityField() {
        for (SubscriptionProductCharge__c subscriptionProductCharge : (List<SubscriptionProductCharge__c>) records) {
            subscriptionProductCharge.Quantity__c = subscriptionProductCharge.Quantity__c == 0 || subscriptionProductCharge.Quantity__c == null ? 1 : subscriptionProductCharge.Quantity__c;
        }
    }

    private Map<Id, Subscription__c> subscriptionById {
        get {
            if (subscriptionById == null) {
                subscriptionById = new Map<Id, Subscription__c>(
                    SubscriptionSelector.newInstance().selectById((Set<Id>)JSON.deserialize(JSON.serialize(getFieldValues(SubscriptionProductCharge__c.Subscription__c)), Set<Id>.class)));
            }
            return subscriptionById;
        }
        set;
    }

    public void populateEffectiveEndDate() {
        fflib_ISObjectUnitOfWork unitOfWork = Application.UnitOfWork.newInstance(new List<SObjectType>{
                SubscriptionProductCharge__c.SObjectType
        });
        for(SubscriptionProductCharge__c subscriptionProductCharge : (List<SubscriptionProductCharge__c>)getRecordsWithNotBlankFieldValues(new Set<Schema.SObjectField> {Schema.SubscriptionProductCharge__c.Subscription__c})) {
            if(subscriptionProductCharge.EffectiveEndDate__c == null) {
                unitOfWork.registerDirty(new SubscriptionProductCharge__c(
                        Id = subscriptionProductCharge.Id,
                        EffectiveEndDate__c = subscriptionById?.get(subscriptionProductCharge.Subscription__c)?.SubscriptionEndDate__c
                ));
            }
        }
        unitOfWork.commitWork();
    }

    public class Constructor implements fflib_SObjectDomain.IConstructable {
        public fflib_SObjectDomain construct(List<SObject> records) {
            return new DAZNSubscriptionProductChargeDomain(records);
        }
    }
}