src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>AutoNumber__c</fullName>
        <description>Auto number to use for setting on the SKU</description>
        <displayFormat>{0000000}</displayFormat>
        <label>AutoNumber</label>
        <type>AutoNumber</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Product_Family_SKU_Mapping__mdt.object
<CustomObject>
    <fields>
        <fullName>Populate_External_Id_By_Record_Id__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Check to populate product external id with record id</description>
        <label>Populate External Id By Record Id</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SKU_Prefix__c</fullName>
        <description>SKU prefix based on the family</description>
        <label>SKU Prefix</label>
        <length>10</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Product Family SKU Mapping</label>
    <pluralLabel>Product Family SKU Mappings</pluralLabel>
</CustomObject>

src/objects/Subscription__c.object
<CustomObject>
    <description>A subscription is a product or service that has recurring charges, such as a monthly flat fee or charges based on usage. Subscriptions can also include one-time charges, such as activation fees.</description>
    <label>DAZN Subscription</label>
    <nameField>
        <displayFormat>A-S{00000000}</displayFormat>
        <label>Subscription Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DAZN Subscriptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/Product2Domain.cls
public with sharing class Product2Domain extends ApplicationDomain {

    private Map<String, Product_Family_SKU_Mapping__mdt> productFamilySKUMappingsByName {
        get {
            if(productFamilySKUMappingsByName == null) {
                productFamilySKUMappingsByName = Product_Family_SKU_Mapping__mdt.getAll();
            }
            return productFamilySKUMappingsByName;
        }
        private set;
    }

    public static Product2Domain newInstance(List<Subscription__c> recordList) {
        return (Product2Domain) Application.Domain.newInstance(recordList);
    }

    public Product2Domain(List<Product2> products) {
        super(products);
    }

    public override void onAfterInsert() {
        populateSKUAndExternalId();
        createStandardPriceBook();
    }

    public void populateSKUAndExternalId() {
        fflib_ISObjectUnitOfWork uow = Application.UnitOfWork.newInstance();
        for (Product2 productRecord : (List<Product2>) Records) {
            String skuPrefix =  productFamilySKUMappingsByName?.get(productRecord.Family)?.SKU_Prefix__c != null ? productFamilySKUMappingsByName?.get(productRecord.Family)?.SKU_Prefix__c : 'SKU';
            Product2 productRecord2 = new Product2(Id = productRecord.Id);
            productRecord2.StockKeepingUnit = skuPrefix +'-' +productRecord.AutoNumber__c;
            productRecord2.ExternalId = productFamilySKUMappingsByName?.get(productRecord.Family)?.Populate_External_Id_By_Record_Id__c != false ? String.valueOf(productRecord.Id) : productRecord2.ExternalId;
            uow.registerDirty(productRecord2);
        }
        fflib_SObjectDomain.getTriggerEvent(Product2Domain.class).disableAll();
        uow.commitWork();
    }

    public void createStandardPriceBook() {
        fflib_ISObjectUnitOfWork uow = Application.UnitOfWork.newInstance();
        List<Pricebook2> priceBookList = PriceBookSelector.newInstance().selectStandardPricebook();
        for (Product2 productRecord : (List<Product2>) Records) {
            PricebookEntry pricebookEntryRecord = new PricebookEntry();
            pricebookEntryRecord.Pricebook2Id = priceBookList[0].Id;
            pricebookEntryRecord.Product2Id = productRecord.Id;
            pricebookEntryRecord.CurrencyIsoCode = 'EUR';
            pricebookEntryRecord.UnitPrice = 0.0;
            pricebookEntryRecord.IsActive = true;

            uow.registerNew(pricebookEntryRecord);
        }
        uow.commitWork();
    }

    public class Constructor implements fflib_SObjectDomain.IConstructable {
        public fflib_SObjectDomain construct(List<SObject> sObjectList) {
            return new Product2Domain(sObjectList);
        }
    }

}